/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UnsubscribeForScriptsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnsubscribeForScriptsRequest{}

// UnsubscribeForScriptsRequest struct for UnsubscribeForScriptsRequest
type UnsubscribeForScriptsRequest struct {
	// If empty, unsubscribe all scripts
		Scripts []string `json:"scripts,omitempty"`
		SubscriptionId *string `json:"subscriptionId,omitempty"`
}

// NewUnsubscribeForScriptsRequest instantiates a new UnsubscribeForScriptsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnsubscribeForScriptsRequest() *UnsubscribeForScriptsRequest {
	this := UnsubscribeForScriptsRequest{}
	return &this
}

// NewUnsubscribeForScriptsRequestWithDefaults instantiates a new UnsubscribeForScriptsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnsubscribeForScriptsRequestWithDefaults() *UnsubscribeForScriptsRequest {
	this := UnsubscribeForScriptsRequest{}
	return &this
}

// GetScripts returns the Scripts field value if set, zero value otherwise.
func (o *UnsubscribeForScriptsRequest) GetScripts() []string {
	if o == nil || IsNil(o.Scripts) {
		var ret []string
		return ret
	}
	return o.Scripts
}

// GetScriptsOk returns a tuple with the Scripts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnsubscribeForScriptsRequest) GetScriptsOk() ([]string, bool) {
	if o == nil || IsNil(o.Scripts) {
		return nil, false
	}
	return o.Scripts, true
}

// HasScripts returns a boolean if a field has been set.
func (o *UnsubscribeForScriptsRequest) HasScripts() bool {
	if o != nil && !IsNil(o.Scripts) {
		return true
	}

	return false
}

// SetScripts gets a reference to the given []string and assigns it to the Scripts field.
func (o *UnsubscribeForScriptsRequest) SetScripts(v []string) {
	o.Scripts = v
}

// GetSubscriptionId returns the SubscriptionId field value if set, zero value otherwise.
func (o *UnsubscribeForScriptsRequest) GetSubscriptionId() string {
	if o == nil || IsNil(o.SubscriptionId) {
		var ret string
		return ret
	}
	return *o.SubscriptionId
}

// GetSubscriptionIdOk returns a tuple with the SubscriptionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnsubscribeForScriptsRequest) GetSubscriptionIdOk() (*string, bool) {
	if o == nil || IsNil(o.SubscriptionId) {
		return nil, false
	}
	return o.SubscriptionId, true
}

// HasSubscriptionId returns a boolean if a field has been set.
func (o *UnsubscribeForScriptsRequest) HasSubscriptionId() bool {
	if o != nil && !IsNil(o.SubscriptionId) {
		return true
	}

	return false
}

// SetSubscriptionId gets a reference to the given string and assigns it to the SubscriptionId field.
func (o *UnsubscribeForScriptsRequest) SetSubscriptionId(v string) {
	o.SubscriptionId = &v
}

func (o UnsubscribeForScriptsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnsubscribeForScriptsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Scripts) {
		toSerialize["scripts"] = o.Scripts
	}
	if !IsNil(o.SubscriptionId) {
		toSerialize["subscriptionId"] = o.SubscriptionId
	}
	return toSerialize, nil
}

type NullableUnsubscribeForScriptsRequest struct {
	value *UnsubscribeForScriptsRequest
	isSet bool
}

func (v NullableUnsubscribeForScriptsRequest) Get() *UnsubscribeForScriptsRequest {
	return v.value
}

func (v *NullableUnsubscribeForScriptsRequest) Set(val *UnsubscribeForScriptsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUnsubscribeForScriptsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUnsubscribeForScriptsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnsubscribeForScriptsRequest(val *UnsubscribeForScriptsRequest) *NullableUnsubscribeForScriptsRequest {
	return &NullableUnsubscribeForScriptsRequest{value: val, isSet: true}
}

func (v NullableUnsubscribeForScriptsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnsubscribeForScriptsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


