/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetVtxoTreeResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetVtxoTreeResponse{}

// GetVtxoTreeResponse struct for GetVtxoTreeResponse
type GetVtxoTreeResponse struct {
		Page *IndexerPageResponse `json:"page,omitempty"`
		VtxoTree []IndexerNode `json:"vtxoTree,omitempty"`
}

// NewGetVtxoTreeResponse instantiates a new GetVtxoTreeResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetVtxoTreeResponse() *GetVtxoTreeResponse {
	this := GetVtxoTreeResponse{}
	return &this
}

// NewGetVtxoTreeResponseWithDefaults instantiates a new GetVtxoTreeResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetVtxoTreeResponseWithDefaults() *GetVtxoTreeResponse {
	this := GetVtxoTreeResponse{}
	return &this
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *GetVtxoTreeResponse) GetPage() IndexerPageResponse {
	if o == nil || IsNil(o.Page) {
		var ret IndexerPageResponse
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVtxoTreeResponse) GetPageOk() (*IndexerPageResponse, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *GetVtxoTreeResponse) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given IndexerPageResponse and assigns it to the Page field.
func (o *GetVtxoTreeResponse) SetPage(v IndexerPageResponse) {
	o.Page = &v
}

// GetVtxoTree returns the VtxoTree field value if set, zero value otherwise.
func (o *GetVtxoTreeResponse) GetVtxoTree() []IndexerNode {
	if o == nil || IsNil(o.VtxoTree) {
		var ret []IndexerNode
		return ret
	}
	return o.VtxoTree
}

// GetVtxoTreeOk returns a tuple with the VtxoTree field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVtxoTreeResponse) GetVtxoTreeOk() ([]IndexerNode, bool) {
	if o == nil || IsNil(o.VtxoTree) {
		return nil, false
	}
	return o.VtxoTree, true
}

// HasVtxoTree returns a boolean if a field has been set.
func (o *GetVtxoTreeResponse) HasVtxoTree() bool {
	if o != nil && !IsNil(o.VtxoTree) {
		return true
	}

	return false
}

// SetVtxoTree gets a reference to the given []IndexerNode and assigns it to the VtxoTree field.
func (o *GetVtxoTreeResponse) SetVtxoTree(v []IndexerNode) {
	o.VtxoTree = v
}

func (o GetVtxoTreeResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetVtxoTreeResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !IsNil(o.VtxoTree) {
		toSerialize["vtxoTree"] = o.VtxoTree
	}
	return toSerialize, nil
}

type NullableGetVtxoTreeResponse struct {
	value *GetVtxoTreeResponse
	isSet bool
}

func (v NullableGetVtxoTreeResponse) Get() *GetVtxoTreeResponse {
	return v.value
}

func (v *NullableGetVtxoTreeResponse) Set(val *GetVtxoTreeResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetVtxoTreeResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetVtxoTreeResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetVtxoTreeResponse(val *GetVtxoTreeResponse) *NullableGetVtxoTreeResponse {
	return &NullableGetVtxoTreeResponse{value: val, isSet: true}
}

func (v NullableGetVtxoTreeResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetVtxoTreeResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


