/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetAssetDetailsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAssetDetailsRequest{}

// GetAssetDetailsRequest struct for GetAssetDetailsRequest
type GetAssetDetailsRequest struct {
		AssetId *string `json:"assetId,omitempty"`
}

// NewGetAssetDetailsRequest instantiates a new GetAssetDetailsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAssetDetailsRequest() *GetAssetDetailsRequest {
	this := GetAssetDetailsRequest{}
	return &this
}

// NewGetAssetDetailsRequestWithDefaults instantiates a new GetAssetDetailsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAssetDetailsRequestWithDefaults() *GetAssetDetailsRequest {
	this := GetAssetDetailsRequest{}
	return &this
}

// GetAssetId returns the AssetId field value if set, zero value otherwise.
func (o *GetAssetDetailsRequest) GetAssetId() string {
	if o == nil || IsNil(o.AssetId) {
		var ret string
		return ret
	}
	return *o.AssetId
}

// GetAssetIdOk returns a tuple with the AssetId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAssetDetailsRequest) GetAssetIdOk() (*string, bool) {
	if o == nil || IsNil(o.AssetId) {
		return nil, false
	}
	return o.AssetId, true
}

// HasAssetId returns a boolean if a field has been set.
func (o *GetAssetDetailsRequest) HasAssetId() bool {
	if o != nil && !IsNil(o.AssetId) {
		return true
	}

	return false
}

// SetAssetId gets a reference to the given string and assigns it to the AssetId field.
func (o *GetAssetDetailsRequest) SetAssetId(v string) {
	o.AssetId = &v
}

func (o GetAssetDetailsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAssetDetailsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AssetId) {
		toSerialize["assetId"] = o.AssetId
	}
	return toSerialize, nil
}

type NullableGetAssetDetailsRequest struct {
	value *GetAssetDetailsRequest
	isSet bool
}

func (v NullableGetAssetDetailsRequest) Get() *GetAssetDetailsRequest {
	return v.value
}

func (v *NullableGetAssetDetailsRequest) Set(val *GetAssetDetailsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAssetDetailsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAssetDetailsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAssetDetailsRequest(val *GetAssetDetailsRequest) *NullableGetAssetDetailsRequest {
	return &NullableGetAssetDetailsRequest{value: val, isSet: true}
}

func (v NullableGetAssetDetailsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAssetDetailsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


