/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetCommitmentTxRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetCommitmentTxRequest{}

// GetCommitmentTxRequest struct for GetCommitmentTxRequest
type GetCommitmentTxRequest struct {
		Txid *string `json:"txid,omitempty"`
}

// NewGetCommitmentTxRequest instantiates a new GetCommitmentTxRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCommitmentTxRequest() *GetCommitmentTxRequest {
	this := GetCommitmentTxRequest{}
	return &this
}

// NewGetCommitmentTxRequestWithDefaults instantiates a new GetCommitmentTxRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCommitmentTxRequestWithDefaults() *GetCommitmentTxRequest {
	this := GetCommitmentTxRequest{}
	return &this
}

// GetTxid returns the Txid field value if set, zero value otherwise.
func (o *GetCommitmentTxRequest) GetTxid() string {
	if o == nil || IsNil(o.Txid) {
		var ret string
		return ret
	}
	return *o.Txid
}

// GetTxidOk returns a tuple with the Txid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCommitmentTxRequest) GetTxidOk() (*string, bool) {
	if o == nil || IsNil(o.Txid) {
		return nil, false
	}
	return o.Txid, true
}

// HasTxid returns a boolean if a field has been set.
func (o *GetCommitmentTxRequest) HasTxid() bool {
	if o != nil && !IsNil(o.Txid) {
		return true
	}

	return false
}

// SetTxid gets a reference to the given string and assigns it to the Txid field.
func (o *GetCommitmentTxRequest) SetTxid(v string) {
	o.Txid = &v
}

func (o GetCommitmentTxRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetCommitmentTxRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Txid) {
		toSerialize["txid"] = o.Txid
	}
	return toSerialize, nil
}

type NullableGetCommitmentTxRequest struct {
	value *GetCommitmentTxRequest
	isSet bool
}

func (v NullableGetCommitmentTxRequest) Get() *GetCommitmentTxRequest {
	return v.value
}

func (v *NullableGetCommitmentTxRequest) Set(val *GetCommitmentTxRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCommitmentTxRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCommitmentTxRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCommitmentTxRequest(val *GetCommitmentTxRequest) *NullableGetCommitmentTxRequest {
	return &NullableGetCommitmentTxRequest{value: val, isSet: true}
}

func (v NullableGetCommitmentTxRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCommitmentTxRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


