/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetVtxoTreeLeavesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetVtxoTreeLeavesRequest{}

// GetVtxoTreeLeavesRequest struct for GetVtxoTreeLeavesRequest
type GetVtxoTreeLeavesRequest struct {
	BatchOutpoint *IndexerOutpoint `json:"batchOutpoint,omitempty"`
	Page *IndexerPageRequest `json:"page,omitempty"`
}

// NewGetVtxoTreeLeavesRequest instantiates a new GetVtxoTreeLeavesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetVtxoTreeLeavesRequest() *GetVtxoTreeLeavesRequest {
	this := GetVtxoTreeLeavesRequest{}
	return &this
}

// NewGetVtxoTreeLeavesRequestWithDefaults instantiates a new GetVtxoTreeLeavesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetVtxoTreeLeavesRequestWithDefaults() *GetVtxoTreeLeavesRequest {
	this := GetVtxoTreeLeavesRequest{}
	return &this
}

// GetBatchOutpoint returns the BatchOutpoint field value if set, zero value otherwise.
func (o *GetVtxoTreeLeavesRequest) GetBatchOutpoint() IndexerOutpoint {
	if o == nil || IsNil(o.BatchOutpoint) {
		var ret IndexerOutpoint
		return ret
	}
	return *o.BatchOutpoint
}

// GetBatchOutpointOk returns a tuple with the BatchOutpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVtxoTreeLeavesRequest) GetBatchOutpointOk() (*IndexerOutpoint, bool) {
	if o == nil || IsNil(o.BatchOutpoint) {
		return nil, false
	}
	return o.BatchOutpoint, true
}

// HasBatchOutpoint returns a boolean if a field has been set.
func (o *GetVtxoTreeLeavesRequest) HasBatchOutpoint() bool {
	if o != nil && !IsNil(o.BatchOutpoint) {
		return true
	}

	return false
}

// SetBatchOutpoint gets a reference to the given IndexerOutpoint and assigns it to the BatchOutpoint field.
func (o *GetVtxoTreeLeavesRequest) SetBatchOutpoint(v IndexerOutpoint) {
	o.BatchOutpoint = &v
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *GetVtxoTreeLeavesRequest) GetPage() IndexerPageRequest {
	if o == nil || IsNil(o.Page) {
		var ret IndexerPageRequest
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVtxoTreeLeavesRequest) GetPageOk() (*IndexerPageRequest, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *GetVtxoTreeLeavesRequest) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given IndexerPageRequest and assigns it to the Page field.
func (o *GetVtxoTreeLeavesRequest) SetPage(v IndexerPageRequest) {
	o.Page = &v
}

func (o GetVtxoTreeLeavesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetVtxoTreeLeavesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BatchOutpoint) {
		toSerialize["batchOutpoint"] = o.BatchOutpoint
	}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	return toSerialize, nil
}

type NullableGetVtxoTreeLeavesRequest struct {
	value *GetVtxoTreeLeavesRequest
	isSet bool
}

func (v NullableGetVtxoTreeLeavesRequest) Get() *GetVtxoTreeLeavesRequest {
	return v.value
}

func (v *NullableGetVtxoTreeLeavesRequest) Set(val *GetVtxoTreeLeavesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetVtxoTreeLeavesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetVtxoTreeLeavesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetVtxoTreeLeavesRequest(val *GetVtxoTreeLeavesRequest) *NullableGetVtxoTreeLeavesRequest {
	return &NullableGetVtxoTreeLeavesRequest{value: val, isSet: true}
}

func (v NullableGetVtxoTreeLeavesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetVtxoTreeLeavesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


