/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetVtxosResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetVtxosResponse{}

// GetVtxosResponse struct for GetVtxosResponse
type GetVtxosResponse struct {
	Page *IndexerPageResponse `json:"page,omitempty"`
	Vtxos []IndexerVtxo `json:"vtxos,omitempty"`
}

// NewGetVtxosResponse instantiates a new GetVtxosResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetVtxosResponse() *GetVtxosResponse {
	this := GetVtxosResponse{}
	return &this
}

// NewGetVtxosResponseWithDefaults instantiates a new GetVtxosResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetVtxosResponseWithDefaults() *GetVtxosResponse {
	this := GetVtxosResponse{}
	return &this
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *GetVtxosResponse) GetPage() IndexerPageResponse {
	if o == nil || IsNil(o.Page) {
		var ret IndexerPageResponse
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVtxosResponse) GetPageOk() (*IndexerPageResponse, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *GetVtxosResponse) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given IndexerPageResponse and assigns it to the Page field.
func (o *GetVtxosResponse) SetPage(v IndexerPageResponse) {
	o.Page = &v
}

// GetVtxos returns the Vtxos field value if set, zero value otherwise.
func (o *GetVtxosResponse) GetVtxos() []IndexerVtxo {
	if o == nil || IsNil(o.Vtxos) {
		var ret []IndexerVtxo
		return ret
	}
	return o.Vtxos
}

// GetVtxosOk returns a tuple with the Vtxos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVtxosResponse) GetVtxosOk() ([]IndexerVtxo, bool) {
	if o == nil || IsNil(o.Vtxos) {
		return nil, false
	}
	return o.Vtxos, true
}

// HasVtxos returns a boolean if a field has been set.
func (o *GetVtxosResponse) HasVtxos() bool {
	if o != nil && !IsNil(o.Vtxos) {
		return true
	}

	return false
}

// SetVtxos gets a reference to the given []IndexerVtxo and assigns it to the Vtxos field.
func (o *GetVtxosResponse) SetVtxos(v []IndexerVtxo) {
	o.Vtxos = v
}

func (o GetVtxosResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetVtxosResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !IsNil(o.Vtxos) {
		toSerialize["vtxos"] = o.Vtxos
	}
	return toSerialize, nil
}

type NullableGetVtxosResponse struct {
	value *GetVtxosResponse
	isSet bool
}

func (v NullableGetVtxosResponse) Get() *GetVtxosResponse {
	return v.value
}

func (v *NullableGetVtxosResponse) Set(val *GetVtxosResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetVtxosResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetVtxosResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetVtxosResponse(val *GetVtxosResponse) *NullableGetVtxosResponse {
	return &NullableGetVtxosResponse{value: val, isSet: true}
}

func (v NullableGetVtxosResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetVtxosResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


