/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PageResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PageResponse{}

// PageResponse struct for PageResponse
type PageResponse struct {
		Current *int32 `json:"current,omitempty"`
		Next *int32 `json:"next,omitempty"`
		Total *int32 `json:"total,omitempty"`
}

// NewPageResponse instantiates a new PageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPageResponse() *PageResponse {
	this := PageResponse{}
	return &this
}

// NewPageResponseWithDefaults instantiates a new PageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPageResponseWithDefaults() *PageResponse {
	this := PageResponse{}
	return &this
}

// GetCurrent returns the Current field value if set, zero value otherwise.
func (o *PageResponse) GetCurrent() int32 {
	if o == nil || IsNil(o.Current) {
		var ret int32
		return ret
	}
	return *o.Current
}

// GetCurrentOk returns a tuple with the Current field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PageResponse) GetCurrentOk() (*int32, bool) {
	if o == nil || IsNil(o.Current) {
		return nil, false
	}
	return o.Current, true
}

// HasCurrent returns a boolean if a field has been set.
func (o *PageResponse) HasCurrent() bool {
	if o != nil && !IsNil(o.Current) {
		return true
	}

	return false
}

// SetCurrent gets a reference to the given int32 and assigns it to the Current field.
func (o *PageResponse) SetCurrent(v int32) {
	o.Current = &v
}

// GetNext returns the Next field value if set, zero value otherwise.
func (o *PageResponse) GetNext() int32 {
	if o == nil || IsNil(o.Next) {
		var ret int32
		return ret
	}
	return *o.Next
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PageResponse) GetNextOk() (*int32, bool) {
	if o == nil || IsNil(o.Next) {
		return nil, false
	}
	return o.Next, true
}

// HasNext returns a boolean if a field has been set.
func (o *PageResponse) HasNext() bool {
	if o != nil && !IsNil(o.Next) {
		return true
	}

	return false
}

// SetNext gets a reference to the given int32 and assigns it to the Next field.
func (o *PageResponse) SetNext(v int32) {
	o.Next = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *PageResponse) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PageResponse) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *PageResponse) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *PageResponse) SetTotal(v int32) {
	o.Total = &v
}

func (o PageResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PageResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Current) {
		toSerialize["current"] = o.Current
	}
	if !IsNil(o.Next) {
		toSerialize["next"] = o.Next
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullablePageResponse struct {
	value *PageResponse
	isSet bool
}

func (v NullablePageResponse) Get() *PageResponse {
	return v.value
}

func (v *NullablePageResponse) Set(val *PageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePageResponse(val *PageResponse) *NullablePageResponse {
	return &NullablePageResponse{value: val, isSet: true}
}

func (v NullablePageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePageResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


