/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetForfeitTxsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetForfeitTxsRequest{}

// GetForfeitTxsRequest struct for GetForfeitTxsRequest
type GetForfeitTxsRequest struct {
		Page *IndexerPageRequest `json:"page,omitempty"`
		Txid *string `json:"txid,omitempty"`
}

// NewGetForfeitTxsRequest instantiates a new GetForfeitTxsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetForfeitTxsRequest() *GetForfeitTxsRequest {
	this := GetForfeitTxsRequest{}
	return &this
}

// NewGetForfeitTxsRequestWithDefaults instantiates a new GetForfeitTxsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetForfeitTxsRequestWithDefaults() *GetForfeitTxsRequest {
	this := GetForfeitTxsRequest{}
	return &this
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *GetForfeitTxsRequest) GetPage() IndexerPageRequest {
	if o == nil || IsNil(o.Page) {
		var ret IndexerPageRequest
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetForfeitTxsRequest) GetPageOk() (*IndexerPageRequest, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *GetForfeitTxsRequest) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given IndexerPageRequest and assigns it to the Page field.
func (o *GetForfeitTxsRequest) SetPage(v IndexerPageRequest) {
	o.Page = &v
}

// GetTxid returns the Txid field value if set, zero value otherwise.
func (o *GetForfeitTxsRequest) GetTxid() string {
	if o == nil || IsNil(o.Txid) {
		var ret string
		return ret
	}
	return *o.Txid
}

// GetTxidOk returns a tuple with the Txid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetForfeitTxsRequest) GetTxidOk() (*string, bool) {
	if o == nil || IsNil(o.Txid) {
		return nil, false
	}
	return o.Txid, true
}

// HasTxid returns a boolean if a field has been set.
func (o *GetForfeitTxsRequest) HasTxid() bool {
	if o != nil && !IsNil(o.Txid) {
		return true
	}

	return false
}

// SetTxid gets a reference to the given string and assigns it to the Txid field.
func (o *GetForfeitTxsRequest) SetTxid(v string) {
	o.Txid = &v
}

func (o GetForfeitTxsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetForfeitTxsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !IsNil(o.Txid) {
		toSerialize["txid"] = o.Txid
	}
	return toSerialize, nil
}

type NullableGetForfeitTxsRequest struct {
	value *GetForfeitTxsRequest
	isSet bool
}

func (v NullableGetForfeitTxsRequest) Get() *GetForfeitTxsRequest {
	return v.value
}

func (v *NullableGetForfeitTxsRequest) Set(val *GetForfeitTxsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetForfeitTxsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetForfeitTxsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetForfeitTxsRequest(val *GetForfeitTxsRequest) *NullableGetForfeitTxsRequest {
	return &NullableGetForfeitTxsRequest{value: val, isSet: true}
}

func (v NullableGetForfeitTxsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetForfeitTxsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


