/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the IndexerPageRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IndexerPageRequest{}

// IndexerPageRequest struct for IndexerPageRequest
type IndexerPageRequest struct {
	Index *int32 `json:"index,omitempty"`
	Size *int32 `json:"size,omitempty"`
}

// NewIndexerPageRequest instantiates a new IndexerPageRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIndexerPageRequest() *IndexerPageRequest {
	this := IndexerPageRequest{}
	return &this
}

// NewIndexerPageRequestWithDefaults instantiates a new IndexerPageRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIndexerPageRequestWithDefaults() *IndexerPageRequest {
	this := IndexerPageRequest{}
	return &this
}

// GetIndex returns the Index field value if set, zero value otherwise.
func (o *IndexerPageRequest) GetIndex() int32 {
	if o == nil || IsNil(o.Index) {
		var ret int32
		return ret
	}
	return *o.Index
}

// GetIndexOk returns a tuple with the Index field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndexerPageRequest) GetIndexOk() (*int32, bool) {
	if o == nil || IsNil(o.Index) {
		return nil, false
	}
	return o.Index, true
}

// HasIndex returns a boolean if a field has been set.
func (o *IndexerPageRequest) HasIndex() bool {
	if o != nil && !IsNil(o.Index) {
		return true
	}

	return false
}

// SetIndex gets a reference to the given int32 and assigns it to the Index field.
func (o *IndexerPageRequest) SetIndex(v int32) {
	o.Index = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *IndexerPageRequest) GetSize() int32 {
	if o == nil || IsNil(o.Size) {
		var ret int32
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndexerPageRequest) GetSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *IndexerPageRequest) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given int32 and assigns it to the Size field.
func (o *IndexerPageRequest) SetSize(v int32) {
	o.Size = &v
}

func (o IndexerPageRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IndexerPageRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Index) {
		toSerialize["index"] = o.Index
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	return toSerialize, nil
}

type NullableIndexerPageRequest struct {
	value *IndexerPageRequest
	isSet bool
}

func (v NullableIndexerPageRequest) Get() *IndexerPageRequest {
	return v.value
}

func (v *NullableIndexerPageRequest) Set(val *IndexerPageRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableIndexerPageRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableIndexerPageRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIndexerPageRequest(val *IndexerPageRequest) *NullableIndexerPageRequest {
	return &NullableIndexerPageRequest{value: val, isSet: true}
}

func (v NullableIndexerPageRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIndexerPageRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


