/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the IndexerBatch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IndexerBatch{}

// IndexerBatch struct for IndexerBatch
type IndexerBatch struct {
	ExpiresAt *int64 `json:"expiresAt,omitempty"`
	Swept *bool `json:"swept,omitempty"`
	TotalOutputAmount *int32 `json:"totalOutputAmount,omitempty"`
	TotalOutputVtxos *int32 `json:"totalOutputVtxos,omitempty"`
}

// NewIndexerBatch instantiates a new IndexerBatch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIndexerBatch() *IndexerBatch {
	this := IndexerBatch{}
	return &this
}

// NewIndexerBatchWithDefaults instantiates a new IndexerBatch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIndexerBatchWithDefaults() *IndexerBatch {
	this := IndexerBatch{}
	return &this
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *IndexerBatch) GetExpiresAt() int64 {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret int64
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndexerBatch) GetExpiresAtOk() (*int64, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *IndexerBatch) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given int64 and assigns it to the ExpiresAt field.
func (o *IndexerBatch) SetExpiresAt(v int64) {
	o.ExpiresAt = &v
}

// GetSwept returns the Swept field value if set, zero value otherwise.
func (o *IndexerBatch) GetSwept() bool {
	if o == nil || IsNil(o.Swept) {
		var ret bool
		return ret
	}
	return *o.Swept
}

// GetSweptOk returns a tuple with the Swept field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndexerBatch) GetSweptOk() (*bool, bool) {
	if o == nil || IsNil(o.Swept) {
		return nil, false
	}
	return o.Swept, true
}

// HasSwept returns a boolean if a field has been set.
func (o *IndexerBatch) HasSwept() bool {
	if o != nil && !IsNil(o.Swept) {
		return true
	}

	return false
}

// SetSwept gets a reference to the given bool and assigns it to the Swept field.
func (o *IndexerBatch) SetSwept(v bool) {
	o.Swept = &v
}

// GetTotalOutputAmount returns the TotalOutputAmount field value if set, zero value otherwise.
func (o *IndexerBatch) GetTotalOutputAmount() int32 {
	if o == nil || IsNil(o.TotalOutputAmount) {
		var ret int32
		return ret
	}
	return *o.TotalOutputAmount
}

// GetTotalOutputAmountOk returns a tuple with the TotalOutputAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndexerBatch) GetTotalOutputAmountOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalOutputAmount) {
		return nil, false
	}
	return o.TotalOutputAmount, true
}

// HasTotalOutputAmount returns a boolean if a field has been set.
func (o *IndexerBatch) HasTotalOutputAmount() bool {
	if o != nil && !IsNil(o.TotalOutputAmount) {
		return true
	}

	return false
}

// SetTotalOutputAmount gets a reference to the given int32 and assigns it to the TotalOutputAmount field.
func (o *IndexerBatch) SetTotalOutputAmount(v int32) {
	o.TotalOutputAmount = &v
}

// GetTotalOutputVtxos returns the TotalOutputVtxos field value if set, zero value otherwise.
func (o *IndexerBatch) GetTotalOutputVtxos() int32 {
	if o == nil || IsNil(o.TotalOutputVtxos) {
		var ret int32
		return ret
	}
	return *o.TotalOutputVtxos
}

// GetTotalOutputVtxosOk returns a tuple with the TotalOutputVtxos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndexerBatch) GetTotalOutputVtxosOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalOutputVtxos) {
		return nil, false
	}
	return o.TotalOutputVtxos, true
}

// HasTotalOutputVtxos returns a boolean if a field has been set.
func (o *IndexerBatch) HasTotalOutputVtxos() bool {
	if o != nil && !IsNil(o.TotalOutputVtxos) {
		return true
	}

	return false
}

// SetTotalOutputVtxos gets a reference to the given int32 and assigns it to the TotalOutputVtxos field.
func (o *IndexerBatch) SetTotalOutputVtxos(v int32) {
	o.TotalOutputVtxos = &v
}

func (o IndexerBatch) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IndexerBatch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ExpiresAt) {
		toSerialize["expiresAt"] = o.ExpiresAt
	}
	if !IsNil(o.Swept) {
		toSerialize["swept"] = o.Swept
	}
	if !IsNil(o.TotalOutputAmount) {
		toSerialize["totalOutputAmount"] = o.TotalOutputAmount
	}
	if !IsNil(o.TotalOutputVtxos) {
		toSerialize["totalOutputVtxos"] = o.TotalOutputVtxos
	}
	return toSerialize, nil
}

type NullableIndexerBatch struct {
	value *IndexerBatch
	isSet bool
}

func (v NullableIndexerBatch) Get() *IndexerBatch {
	return v.value
}

func (v *NullableIndexerBatch) Set(val *IndexerBatch) {
	v.value = val
	v.isSet = true
}

func (v NullableIndexerBatch) IsSet() bool {
	return v.isSet
}

func (v *NullableIndexerBatch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIndexerBatch(val *IndexerBatch) *NullableIndexerBatch {
	return &NullableIndexerBatch{value: val, isSet: true}
}

func (v NullableIndexerBatch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIndexerBatch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


