/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetBatchSweepTransactionsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetBatchSweepTransactionsRequest{}

// GetBatchSweepTransactionsRequest struct for GetBatchSweepTransactionsRequest
type GetBatchSweepTransactionsRequest struct {
		BatchOutpoint *IndexerOutpoint `json:"batchOutpoint,omitempty"`
}

// NewGetBatchSweepTransactionsRequest instantiates a new GetBatchSweepTransactionsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetBatchSweepTransactionsRequest() *GetBatchSweepTransactionsRequest {
	this := GetBatchSweepTransactionsRequest{}
	return &this
}

// NewGetBatchSweepTransactionsRequestWithDefaults instantiates a new GetBatchSweepTransactionsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetBatchSweepTransactionsRequestWithDefaults() *GetBatchSweepTransactionsRequest {
	this := GetBatchSweepTransactionsRequest{}
	return &this
}

// GetBatchOutpoint returns the BatchOutpoint field value if set, zero value otherwise.
func (o *GetBatchSweepTransactionsRequest) GetBatchOutpoint() IndexerOutpoint {
	if o == nil || IsNil(o.BatchOutpoint) {
		var ret IndexerOutpoint
		return ret
	}
	return *o.BatchOutpoint
}

// GetBatchOutpointOk returns a tuple with the BatchOutpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBatchSweepTransactionsRequest) GetBatchOutpointOk() (*IndexerOutpoint, bool) {
	if o == nil || IsNil(o.BatchOutpoint) {
		return nil, false
	}
	return o.BatchOutpoint, true
}

// HasBatchOutpoint returns a boolean if a field has been set.
func (o *GetBatchSweepTransactionsRequest) HasBatchOutpoint() bool {
	if o != nil && !IsNil(o.BatchOutpoint) {
		return true
	}

	return false
}

// SetBatchOutpoint gets a reference to the given IndexerOutpoint and assigns it to the BatchOutpoint field.
func (o *GetBatchSweepTransactionsRequest) SetBatchOutpoint(v IndexerOutpoint) {
	o.BatchOutpoint = &v
}

func (o GetBatchSweepTransactionsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetBatchSweepTransactionsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BatchOutpoint) {
		toSerialize["batchOutpoint"] = o.BatchOutpoint
	}
	return toSerialize, nil
}

type NullableGetBatchSweepTransactionsRequest struct {
	value *GetBatchSweepTransactionsRequest
	isSet bool
}

func (v NullableGetBatchSweepTransactionsRequest) Get() *GetBatchSweepTransactionsRequest {
	return v.value
}

func (v *NullableGetBatchSweepTransactionsRequest) Set(val *GetBatchSweepTransactionsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetBatchSweepTransactionsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetBatchSweepTransactionsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetBatchSweepTransactionsRequest(val *GetBatchSweepTransactionsRequest) *NullableGetBatchSweepTransactionsRequest {
	return &NullableGetBatchSweepTransactionsRequest{value: val, isSet: true}
}

func (v NullableGetBatchSweepTransactionsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetBatchSweepTransactionsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


