/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetCommitmentTxResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetCommitmentTxResponse{}

// GetCommitmentTxResponse struct for GetCommitmentTxResponse
type GetCommitmentTxResponse struct {
	Batches map[string]IndexerBatch `json:"batches,omitempty"`
	EndedAt *int64 `json:"endedAt,omitempty"`
	StartedAt *int64 `json:"startedAt,omitempty"`
	TotalInputAmount *int32 `json:"totalInputAmount,omitempty"`
	TotalInputVtxos *int32 `json:"totalInputVtxos,omitempty"`
	TotalOutputAmount *int32 `json:"totalOutputAmount,omitempty"`
	TotalOutputVtxos *int32 `json:"totalOutputVtxos,omitempty"`
}

// NewGetCommitmentTxResponse instantiates a new GetCommitmentTxResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCommitmentTxResponse() *GetCommitmentTxResponse {
	this := GetCommitmentTxResponse{}
	return &this
}

// NewGetCommitmentTxResponseWithDefaults instantiates a new GetCommitmentTxResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCommitmentTxResponseWithDefaults() *GetCommitmentTxResponse {
	this := GetCommitmentTxResponse{}
	return &this
}

// GetBatches returns the Batches field value if set, zero value otherwise.
func (o *GetCommitmentTxResponse) GetBatches() map[string]IndexerBatch {
	if o == nil || IsNil(o.Batches) {
		var ret map[string]IndexerBatch
		return ret
	}
	return o.Batches
}

// GetBatchesOk returns a tuple with the Batches field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCommitmentTxResponse) GetBatchesOk() (map[string]IndexerBatch, bool) {
	if o == nil || IsNil(o.Batches) {
		return map[string]IndexerBatch{}, false
	}
	return o.Batches, true
}

// HasBatches returns a boolean if a field has been set.
func (o *GetCommitmentTxResponse) HasBatches() bool {
	if o != nil && !IsNil(o.Batches) {
		return true
	}

	return false
}

// SetBatches gets a reference to the given map[string]IndexerBatch and assigns it to the Batches field.
func (o *GetCommitmentTxResponse) SetBatches(v map[string]IndexerBatch) {
	o.Batches = v
}

// GetEndedAt returns the EndedAt field value if set, zero value otherwise.
func (o *GetCommitmentTxResponse) GetEndedAt() int64 {
	if o == nil || IsNil(o.EndedAt) {
		var ret int64
		return ret
	}
	return *o.EndedAt
}

// GetEndedAtOk returns a tuple with the EndedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCommitmentTxResponse) GetEndedAtOk() (*int64, bool) {
	if o == nil || IsNil(o.EndedAt) {
		return nil, false
	}
	return o.EndedAt, true
}

// HasEndedAt returns a boolean if a field has been set.
func (o *GetCommitmentTxResponse) HasEndedAt() bool {
	if o != nil && !IsNil(o.EndedAt) {
		return true
	}

	return false
}

// SetEndedAt gets a reference to the given int64 and assigns it to the EndedAt field.
func (o *GetCommitmentTxResponse) SetEndedAt(v int64) {
	o.EndedAt = &v
}

// GetStartedAt returns the StartedAt field value if set, zero value otherwise.
func (o *GetCommitmentTxResponse) GetStartedAt() int64 {
	if o == nil || IsNil(o.StartedAt) {
		var ret int64
		return ret
	}
	return *o.StartedAt
}

// GetStartedAtOk returns a tuple with the StartedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCommitmentTxResponse) GetStartedAtOk() (*int64, bool) {
	if o == nil || IsNil(o.StartedAt) {
		return nil, false
	}
	return o.StartedAt, true
}

// HasStartedAt returns a boolean if a field has been set.
func (o *GetCommitmentTxResponse) HasStartedAt() bool {
	if o != nil && !IsNil(o.StartedAt) {
		return true
	}

	return false
}

// SetStartedAt gets a reference to the given int64 and assigns it to the StartedAt field.
func (o *GetCommitmentTxResponse) SetStartedAt(v int64) {
	o.StartedAt = &v
}

// GetTotalInputAmount returns the TotalInputAmount field value if set, zero value otherwise.
func (o *GetCommitmentTxResponse) GetTotalInputAmount() int32 {
	if o == nil || IsNil(o.TotalInputAmount) {
		var ret int32
		return ret
	}
	return *o.TotalInputAmount
}

// GetTotalInputAmountOk returns a tuple with the TotalInputAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCommitmentTxResponse) GetTotalInputAmountOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalInputAmount) {
		return nil, false
	}
	return o.TotalInputAmount, true
}

// HasTotalInputAmount returns a boolean if a field has been set.
func (o *GetCommitmentTxResponse) HasTotalInputAmount() bool {
	if o != nil && !IsNil(o.TotalInputAmount) {
		return true
	}

	return false
}

// SetTotalInputAmount gets a reference to the given int32 and assigns it to the TotalInputAmount field.
func (o *GetCommitmentTxResponse) SetTotalInputAmount(v int32) {
	o.TotalInputAmount = &v
}

// GetTotalInputVtxos returns the TotalInputVtxos field value if set, zero value otherwise.
func (o *GetCommitmentTxResponse) GetTotalInputVtxos() int32 {
	if o == nil || IsNil(o.TotalInputVtxos) {
		var ret int32
		return ret
	}
	return *o.TotalInputVtxos
}

// GetTotalInputVtxosOk returns a tuple with the TotalInputVtxos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCommitmentTxResponse) GetTotalInputVtxosOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalInputVtxos) {
		return nil, false
	}
	return o.TotalInputVtxos, true
}

// HasTotalInputVtxos returns a boolean if a field has been set.
func (o *GetCommitmentTxResponse) HasTotalInputVtxos() bool {
	if o != nil && !IsNil(o.TotalInputVtxos) {
		return true
	}

	return false
}

// SetTotalInputVtxos gets a reference to the given int32 and assigns it to the TotalInputVtxos field.
func (o *GetCommitmentTxResponse) SetTotalInputVtxos(v int32) {
	o.TotalInputVtxos = &v
}

// GetTotalOutputAmount returns the TotalOutputAmount field value if set, zero value otherwise.
func (o *GetCommitmentTxResponse) GetTotalOutputAmount() int32 {
	if o == nil || IsNil(o.TotalOutputAmount) {
		var ret int32
		return ret
	}
	return *o.TotalOutputAmount
}

// GetTotalOutputAmountOk returns a tuple with the TotalOutputAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCommitmentTxResponse) GetTotalOutputAmountOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalOutputAmount) {
		return nil, false
	}
	return o.TotalOutputAmount, true
}

// HasTotalOutputAmount returns a boolean if a field has been set.
func (o *GetCommitmentTxResponse) HasTotalOutputAmount() bool {
	if o != nil && !IsNil(o.TotalOutputAmount) {
		return true
	}

	return false
}

// SetTotalOutputAmount gets a reference to the given int32 and assigns it to the TotalOutputAmount field.
func (o *GetCommitmentTxResponse) SetTotalOutputAmount(v int32) {
	o.TotalOutputAmount = &v
}

// GetTotalOutputVtxos returns the TotalOutputVtxos field value if set, zero value otherwise.
func (o *GetCommitmentTxResponse) GetTotalOutputVtxos() int32 {
	if o == nil || IsNil(o.TotalOutputVtxos) {
		var ret int32
		return ret
	}
	return *o.TotalOutputVtxos
}

// GetTotalOutputVtxosOk returns a tuple with the TotalOutputVtxos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCommitmentTxResponse) GetTotalOutputVtxosOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalOutputVtxos) {
		return nil, false
	}
	return o.TotalOutputVtxos, true
}

// HasTotalOutputVtxos returns a boolean if a field has been set.
func (o *GetCommitmentTxResponse) HasTotalOutputVtxos() bool {
	if o != nil && !IsNil(o.TotalOutputVtxos) {
		return true
	}

	return false
}

// SetTotalOutputVtxos gets a reference to the given int32 and assigns it to the TotalOutputVtxos field.
func (o *GetCommitmentTxResponse) SetTotalOutputVtxos(v int32) {
	o.TotalOutputVtxos = &v
}

func (o GetCommitmentTxResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetCommitmentTxResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Batches) {
		toSerialize["batches"] = o.Batches
	}
	if !IsNil(o.EndedAt) {
		toSerialize["endedAt"] = o.EndedAt
	}
	if !IsNil(o.StartedAt) {
		toSerialize["startedAt"] = o.StartedAt
	}
	if !IsNil(o.TotalInputAmount) {
		toSerialize["totalInputAmount"] = o.TotalInputAmount
	}
	if !IsNil(o.TotalInputVtxos) {
		toSerialize["totalInputVtxos"] = o.TotalInputVtxos
	}
	if !IsNil(o.TotalOutputAmount) {
		toSerialize["totalOutputAmount"] = o.TotalOutputAmount
	}
	if !IsNil(o.TotalOutputVtxos) {
		toSerialize["totalOutputVtxos"] = o.TotalOutputVtxos
	}
	return toSerialize, nil
}

type NullableGetCommitmentTxResponse struct {
	value *GetCommitmentTxResponse
	isSet bool
}

func (v NullableGetCommitmentTxResponse) Get() *GetCommitmentTxResponse {
	return v.value
}

func (v *NullableGetCommitmentTxResponse) Set(val *GetCommitmentTxResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCommitmentTxResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCommitmentTxResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCommitmentTxResponse(val *GetCommitmentTxResponse) *NullableGetCommitmentTxResponse {
	return &NullableGetCommitmentTxResponse{value: val, isSet: true}
}

func (v NullableGetCommitmentTxResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCommitmentTxResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


