/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetVirtualTxsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetVirtualTxsResponse{}

// GetVirtualTxsResponse struct for GetVirtualTxsResponse
type GetVirtualTxsResponse struct {
	Page *IndexerPageResponse `json:"page,omitempty"`
	Txs  []string             `json:"txs,omitempty"`
}

// NewGetVirtualTxsResponse instantiates a new GetVirtualTxsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetVirtualTxsResponse() *GetVirtualTxsResponse {
	this := GetVirtualTxsResponse{}
	return &this
}

// NewGetVirtualTxsResponseWithDefaults instantiates a new GetVirtualTxsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetVirtualTxsResponseWithDefaults() *GetVirtualTxsResponse {
	this := GetVirtualTxsResponse{}
	return &this
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *GetVirtualTxsResponse) GetPage() IndexerPageResponse {
	if o == nil || IsNil(o.Page) {
		var ret IndexerPageResponse
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVirtualTxsResponse) GetPageOk() (*IndexerPageResponse, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *GetVirtualTxsResponse) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given IndexerPageResponse and assigns it to the Page field.
func (o *GetVirtualTxsResponse) SetPage(v IndexerPageResponse) {
	o.Page = &v
}

// GetTransactions returns the Txs field value if set, zero value otherwise.
func (o *GetVirtualTxsResponse) GetTransactions() []string {
	if o == nil || IsNil(o.Txs) {
		var ret []string
		return ret
	}
	return o.Txs
}

// GetTransactionsOk returns a tuple with the Txs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVirtualTxsResponse) GetTransactionsOk() ([]string, bool) {
	if o == nil || IsNil(o.Txs) {
		return nil, false
	}
	return o.Txs, true
}

// HasTxs returns a boolean if a field has been set.
func (o *GetVirtualTxsResponse) HasTxs() bool {
	if o != nil && !IsNil(o.Txs) {
		return true
	}

	return false
}

// SetTxs gets a reference to the given []string and assigns it to the Txs field.
func (o *GetVirtualTxsResponse) SetTxs(v []string) {
	o.Txs = v
}

func (o GetVirtualTxsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetVirtualTxsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !IsNil(o.Txs) {
		toSerialize["txs"] = o.Txs
	}
	return toSerialize, nil
}

type NullableGetVirtualTxsResponse struct {
	value *GetVirtualTxsResponse
	isSet bool
}

func (v NullableGetVirtualTxsResponse) Get() *GetVirtualTxsResponse {
	return v.value
}

func (v *NullableGetVirtualTxsResponse) Set(val *GetVirtualTxsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetVirtualTxsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetVirtualTxsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetVirtualTxsResponse(val *GetVirtualTxsResponse) *NullableGetVirtualTxsResponse {
	return &NullableGetVirtualTxsResponse{value: val, isSet: true}
}

func (v NullableGetVirtualTxsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetVirtualTxsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
