/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SubscribeForTeleportHashResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubscribeForTeleportHashResponse{}

// SubscribeForTeleportHashResponse struct for SubscribeForTeleportHashResponse
type SubscribeForTeleportHashResponse struct {
		SubscriptionId *string `json:"subscriptionId,omitempty"`
}

// NewSubscribeForTeleportHashResponse instantiates a new SubscribeForTeleportHashResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubscribeForTeleportHashResponse() *SubscribeForTeleportHashResponse {
	this := SubscribeForTeleportHashResponse{}
	return &this
}

// NewSubscribeForTeleportHashResponseWithDefaults instantiates a new SubscribeForTeleportHashResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubscribeForTeleportHashResponseWithDefaults() *SubscribeForTeleportHashResponse {
	this := SubscribeForTeleportHashResponse{}
	return &this
}

// GetSubscriptionId returns the SubscriptionId field value if set, zero value otherwise.
func (o *SubscribeForTeleportHashResponse) GetSubscriptionId() string {
	if o == nil || IsNil(o.SubscriptionId) {
		var ret string
		return ret
	}
	return *o.SubscriptionId
}

// GetSubscriptionIdOk returns a tuple with the SubscriptionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscribeForTeleportHashResponse) GetSubscriptionIdOk() (*string, bool) {
	if o == nil || IsNil(o.SubscriptionId) {
		return nil, false
	}
	return o.SubscriptionId, true
}

// HasSubscriptionId returns a boolean if a field has been set.
func (o *SubscribeForTeleportHashResponse) HasSubscriptionId() bool {
	if o != nil && !IsNil(o.SubscriptionId) {
		return true
	}

	return false
}

// SetSubscriptionId gets a reference to the given string and assigns it to the SubscriptionId field.
func (o *SubscribeForTeleportHashResponse) SetSubscriptionId(v string) {
	o.SubscriptionId = &v
}

func (o SubscribeForTeleportHashResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubscribeForTeleportHashResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SubscriptionId) {
		toSerialize["subscriptionId"] = o.SubscriptionId
	}
	return toSerialize, nil
}

type NullableSubscribeForTeleportHashResponse struct {
	value *SubscribeForTeleportHashResponse
	isSet bool
}

func (v NullableSubscribeForTeleportHashResponse) Get() *SubscribeForTeleportHashResponse {
	return v.value
}

func (v *NullableSubscribeForTeleportHashResponse) Set(val *SubscribeForTeleportHashResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSubscribeForTeleportHashResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSubscribeForTeleportHashResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubscribeForTeleportHashResponse(val *SubscribeForTeleportHashResponse) *NullableSubscribeForTeleportHashResponse {
	return &NullableSubscribeForTeleportHashResponse{value: val, isSet: true}
}

func (v NullableSubscribeForTeleportHashResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubscribeForTeleportHashResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


