/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SubscribeForTeleportHashRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubscribeForTeleportHashRequest{}

// SubscribeForTeleportHashRequest struct for SubscribeForTeleportHashRequest
type SubscribeForTeleportHashRequest struct {
	// If set, update an existing subscription
		SubscriptionId *string `json:"subscriptionId,omitempty"`
		TeleportHashes []string `json:"teleportHashes,omitempty"`
}

// NewSubscribeForTeleportHashRequest instantiates a new SubscribeForTeleportHashRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubscribeForTeleportHashRequest() *SubscribeForTeleportHashRequest {
	this := SubscribeForTeleportHashRequest{}
	return &this
}

// NewSubscribeForTeleportHashRequestWithDefaults instantiates a new SubscribeForTeleportHashRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubscribeForTeleportHashRequestWithDefaults() *SubscribeForTeleportHashRequest {
	this := SubscribeForTeleportHashRequest{}
	return &this
}

// GetSubscriptionId returns the SubscriptionId field value if set, zero value otherwise.
func (o *SubscribeForTeleportHashRequest) GetSubscriptionId() string {
	if o == nil || IsNil(o.SubscriptionId) {
		var ret string
		return ret
	}
	return *o.SubscriptionId
}

// GetSubscriptionIdOk returns a tuple with the SubscriptionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscribeForTeleportHashRequest) GetSubscriptionIdOk() (*string, bool) {
	if o == nil || IsNil(o.SubscriptionId) {
		return nil, false
	}
	return o.SubscriptionId, true
}

// HasSubscriptionId returns a boolean if a field has been set.
func (o *SubscribeForTeleportHashRequest) HasSubscriptionId() bool {
	if o != nil && !IsNil(o.SubscriptionId) {
		return true
	}

	return false
}

// SetSubscriptionId gets a reference to the given string and assigns it to the SubscriptionId field.
func (o *SubscribeForTeleportHashRequest) SetSubscriptionId(v string) {
	o.SubscriptionId = &v
}

// GetTeleportHashes returns the TeleportHashes field value if set, zero value otherwise.
func (o *SubscribeForTeleportHashRequest) GetTeleportHashes() []string {
	if o == nil || IsNil(o.TeleportHashes) {
		var ret []string
		return ret
	}
	return o.TeleportHashes
}

// GetTeleportHashesOk returns a tuple with the TeleportHashes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscribeForTeleportHashRequest) GetTeleportHashesOk() ([]string, bool) {
	if o == nil || IsNil(o.TeleportHashes) {
		return nil, false
	}
	return o.TeleportHashes, true
}

// HasTeleportHashes returns a boolean if a field has been set.
func (o *SubscribeForTeleportHashRequest) HasTeleportHashes() bool {
	if o != nil && !IsNil(o.TeleportHashes) {
		return true
	}

	return false
}

// SetTeleportHashes gets a reference to the given []string and assigns it to the TeleportHashes field.
func (o *SubscribeForTeleportHashRequest) SetTeleportHashes(v []string) {
	o.TeleportHashes = v
}

func (o SubscribeForTeleportHashRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubscribeForTeleportHashRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SubscriptionId) {
		toSerialize["subscriptionId"] = o.SubscriptionId
	}
	if !IsNil(o.TeleportHashes) {
		toSerialize["teleportHashes"] = o.TeleportHashes
	}
	return toSerialize, nil
}

type NullableSubscribeForTeleportHashRequest struct {
	value *SubscribeForTeleportHashRequest
	isSet bool
}

func (v NullableSubscribeForTeleportHashRequest) Get() *SubscribeForTeleportHashRequest {
	return v.value
}

func (v *NullableSubscribeForTeleportHashRequest) Set(val *SubscribeForTeleportHashRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSubscribeForTeleportHashRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSubscribeForTeleportHashRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubscribeForTeleportHashRequest(val *SubscribeForTeleportHashRequest) *NullableSubscribeForTeleportHashRequest {
	return &NullableSubscribeForTeleportHashRequest{value: val, isSet: true}
}

func (v NullableSubscribeForTeleportHashRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubscribeForTeleportHashRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


