CREATE TABLE IF NOT EXISTS swap (
  id TEXT PRIMARY KEY,
  from_currency TEXT NOT NULL,
  to_currency TEXT NOT NULL,
  amount INTEGER NOT NULL,
  status INTEGER NOT NULL,
  created_at INTEGER NOT NULL,
  updated_at INTEGER,
  vhtlc_script TEXT NOT NULL,
  funding_txid TEXT,
  redeem_txid TEXT,
  preimage TEXT,
  ln_preimage_hash TEXT,
  ln_invoice TEXT,
  chain_funding_txid TEXT,
  chain_redeem_txid TEXT,
  chain_address TEXT,
  chain_private_key TEXT,
  chain_swap_tree TEXT
);