// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"database/sql"
)

type ChainSwap struct {
	ID                      string
	FromCurrency            string
	ToCurrency              string
	Amount                  int64
	Status                  int64
	UserLockupTxID          sql.NullString
	ServerLockupTxID        sql.NullString
	ClaimTxID               sql.NullString
	ClaimPreimage           string
	RefundTxID              sql.NullString
	UserBtcLockupAddress    sql.NullString
	ErrorMessage            sql.NullString
	BoltzCreateResponseJson sql.NullString
	CreatedAt               sql.NullInt64
	UpdatedAt               sql.NullInt64
}

type HtlcKey struct {
	Address    string
	PrivateKey string
	CreatedAt  int64
}

type Swap struct {
	ID                  string
	Amount              int64
	Timestamp           int64
	ToCurrency          string
	FromCurrency        string
	Status              int64
	SwapType            int64
	Invoice             string
	FundingTxID         sql.NullString
	RedeemTxID          sql.NullString
	VhtlcContractScript string
}
