// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql"
)

type Swap struct {
	ID               string
	FromCurrency     string
	ToCurrency       string
	Amount           int64
	Status           int64
	CreatedAt        int64
	UpdatedAt        sql.NullInt64
	VhtlcScript      string
	FundingTxid      sql.NullString
	RedeemTxid       sql.NullString
	Preimage         sql.NullString
	LnPreimageHash   sql.NullString
	LnInvoice        sql.NullString
	ChainFundingTxid sql.NullString
	ChainRedeemTxid  sql.NullString
	ChainAddress     sql.NullString
	ChainPrivateKey  sql.NullString
	ChainSwapTree    sql.NullString
}
