// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package queries

import (
	"context"
	"database/sql"
)

const insertChainSwap = `-- name: InsertChainSwap :exec
INSERT INTO chain_swap (
    id, from_currency, to_currency, amount, status, user_lockup_tx_id,
    server_lockup_tx_id, claim_tx_id, claim_preimage, refund_tx_id,
    user_btc_lockup_address, error_message, boltz_create_response_json,
    created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertChainSwapParams struct {
	ID                      string
	FromCurrency            string
	ToCurrency              string
	Amount                  int64
	Status                  int64
	UserLockupTxID          sql.NullString
	ServerLockupTxID        sql.NullString
	ClaimTxID               sql.NullString
	ClaimPreimage           string
	RefundTxID              sql.NullString
	UserBtcLockupAddress    sql.NullString
	ErrorMessage            sql.NullString
	BoltzCreateResponseJson sql.NullString
	CreatedAt               sql.NullInt64
	UpdatedAt               sql.NullInt64
}

func (q *Queries) InsertChainSwap(ctx context.Context, arg InsertChainSwapParams) error {
	_, err := q.db.ExecContext(ctx, insertChainSwap,
		arg.ID,
		arg.FromCurrency,
		arg.ToCurrency,
		arg.Amount,
		arg.Status,
		arg.UserLockupTxID,
		arg.ServerLockupTxID,
		arg.ClaimTxID,
		arg.ClaimPreimage,
		arg.RefundTxID,
		arg.UserBtcLockupAddress,
		arg.ErrorMessage,
		arg.BoltzCreateResponseJson,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertSwap = `-- name: InsertSwap :execrows
INSERT OR IGNORE INTO swap (
    id, amount, timestamp, to_currency, from_currency, status, swap_type,
    invoice, funding_tx_id, redeem_tx_id, vhtlc_contract_script
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertSwapParams struct {
	ID                  string
	Amount              int64
	Timestamp           int64
	ToCurrency          string
	FromCurrency        string
	Status              int64
	SwapType            int64
	Invoice             string
	FundingTxID         sql.NullString
	RedeemTxID          sql.NullString
	VhtlcContractScript string
}

func (q *Queries) InsertSwap(ctx context.Context, arg InsertSwapParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertSwap,
		arg.ID,
		arg.Amount,
		arg.Timestamp,
		arg.ToCurrency,
		arg.FromCurrency,
		arg.Status,
		arg.SwapType,
		arg.Invoice,
		arg.FundingTxID,
		arg.RedeemTxID,
		arg.VhtlcContractScript,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const selectChainSwap = `-- name: SelectChainSwap :one
SELECT id, from_currency, to_currency, amount, status, user_lockup_tx_id, server_lockup_tx_id, claim_tx_id, claim_preimage, refund_tx_id, user_btc_lockup_address, error_message, boltz_create_response_json, created_at, updated_at FROM chain_swap
WHERE id = ?1
`

func (q *Queries) SelectChainSwap(ctx context.Context, id string) (ChainSwap, error) {
	row := q.db.QueryRowContext(ctx, selectChainSwap, id)
	var i ChainSwap
	err := row.Scan(
		&i.ID,
		&i.FromCurrency,
		&i.ToCurrency,
		&i.Amount,
		&i.Status,
		&i.UserLockupTxID,
		&i.ServerLockupTxID,
		&i.ClaimTxID,
		&i.ClaimPreimage,
		&i.RefundTxID,
		&i.UserBtcLockupAddress,
		&i.ErrorMessage,
		&i.BoltzCreateResponseJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const selectHTLCKey = `-- name: SelectHTLCKey :one
SELECT address, private_key, created_at FROM htlc_key
WHERE address = ?1
`

func (q *Queries) SelectHTLCKey(ctx context.Context, address string) (HtlcKey, error) {
	row := q.db.QueryRowContext(ctx, selectHTLCKey, address)
	var i HtlcKey
	err := row.Scan(&i.Address, &i.PrivateKey, &i.CreatedAt)
	return i, err
}

const selectSwap = `-- name: SelectSwap :one
SELECT id, amount, timestamp, to_currency, from_currency, status, swap_type, invoice, funding_tx_id, redeem_tx_id, vhtlc_contract_script FROM swap
WHERE id = ?1
`

func (q *Queries) SelectSwap(ctx context.Context, id string) (Swap, error) {
	row := q.db.QueryRowContext(ctx, selectSwap, id)
	var i Swap
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Timestamp,
		&i.ToCurrency,
		&i.FromCurrency,
		&i.Status,
		&i.SwapType,
		&i.Invoice,
		&i.FundingTxID,
		&i.RedeemTxID,
		&i.VhtlcContractScript,
	)
	return i, err
}

const updateChainSwap = `-- name: UpdateChainSwap :execrows
UPDATE chain_swap
SET
    status = ?1,
    user_lockup_tx_id = ?2,
    server_lockup_tx_id = ?3,
    claim_tx_id = ?4,
    refund_tx_id = ?5,
    error_message = ?6,
    boltz_create_response_json = ?7,
    updated_at = ?8
WHERE id = ?9
`

type UpdateChainSwapParams struct {
	Status                  int64
	UserLockupTxID          sql.NullString
	ServerLockupTxID        sql.NullString
	ClaimTxID               sql.NullString
	RefundTxID              sql.NullString
	ErrorMessage            sql.NullString
	BoltzCreateResponseJson sql.NullString
	UpdatedAt               sql.NullInt64
	ID                      string
}

func (q *Queries) UpdateChainSwap(ctx context.Context, arg UpdateChainSwapParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateChainSwap,
		arg.Status,
		arg.UserLockupTxID,
		arg.ServerLockupTxID,
		arg.ClaimTxID,
		arg.RefundTxID,
		arg.ErrorMessage,
		arg.BoltzCreateResponseJson,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateSwap = `-- name: UpdateSwap :execrows
UPDATE swap
SET
    status = ?1,
    funding_tx_id = COALESCE(?2, funding_tx_id),
    redeem_tx_id = COALESCE(?3, redeem_tx_id)
WHERE id = ?4
`

type UpdateSwapParams struct {
	Status      int64
	FundingTxID sql.NullString
	RedeemTxID  sql.NullString
	ID          string
}

func (q *Queries) UpdateSwap(ctx context.Context, arg UpdateSwapParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSwap,
		arg.Status,
		arg.FundingTxID,
		arg.RedeemTxID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertHTLCKey = `-- name: UpsertHTLCKey :exec
INSERT INTO htlc_key (address, private_key, created_at)
VALUES (?, ?, ?)
ON CONFLICT(address) DO UPDATE SET
    private_key = excluded.private_key,
    created_at = excluded.created_at
`

type UpsertHTLCKeyParams struct {
	Address    string
	PrivateKey string
	CreatedAt  int64
}

func (q *Queries) UpsertHTLCKey(ctx context.Context, arg UpsertHTLCKeyParams) error {
	_, err := q.db.ExecContext(ctx, upsertHTLCKey, arg.Address, arg.PrivateKey, arg.CreatedAt)
	return err
}
