// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package queries

import (
	"context"
	"database/sql"
)

const insertSwap = `-- name: InsertSwap :exec
INSERT INTO swap (
    id, from_currency, to_currency, amount, status, created_at, updated_at,
    vhtlc_script, funding_txid, redeem_txid, preimage,
    ln_preimage_hash, ln_invoice,
    chain_funding_txid, chain_redeem_txid, chain_address, chain_private_key,
    chain_swap_tree
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertSwapParams struct {
	ID               string
	FromCurrency     string
	ToCurrency       string
	Amount           int64
	Status           int64
	CreatedAt        int64
	UpdatedAt        sql.NullInt64
	VhtlcScript      string
	FundingTxid      sql.NullString
	RedeemTxid       sql.NullString
	Preimage         sql.NullString
	LnPreimageHash   sql.NullString
	LnInvoice        sql.NullString
	ChainFundingTxid sql.NullString
	ChainRedeemTxid  sql.NullString
	ChainAddress     sql.NullString
	ChainPrivateKey  sql.NullString
	ChainSwapTree    sql.NullString
}

func (q *Queries) InsertSwap(ctx context.Context, arg InsertSwapParams) error {
	_, err := q.db.ExecContext(ctx, insertSwap,
		arg.ID,
		arg.FromCurrency,
		arg.ToCurrency,
		arg.Amount,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.VhtlcScript,
		arg.FundingTxid,
		arg.RedeemTxid,
		arg.Preimage,
		arg.LnPreimageHash,
		arg.LnInvoice,
		arg.ChainFundingTxid,
		arg.ChainRedeemTxid,
		arg.ChainAddress,
		arg.ChainPrivateKey,
		arg.ChainSwapTree,
	)
	return err
}

const selectSwap = `-- name: SelectSwap :one
SELECT id, from_currency, to_currency, amount, status, created_at, updated_at, vhtlc_script, funding_txid, redeem_txid, preimage, ln_preimage_hash, ln_invoice, chain_funding_txid, chain_redeem_txid, chain_address, chain_private_key, chain_swap_tree FROM swap
WHERE id = ?1
`

func (q *Queries) SelectSwap(ctx context.Context, id string) (Swap, error) {
	row := q.db.QueryRowContext(ctx, selectSwap, id)
	var i Swap
	err := row.Scan(
		&i.ID,
		&i.FromCurrency,
		&i.ToCurrency,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VhtlcScript,
		&i.FundingTxid,
		&i.RedeemTxid,
		&i.Preimage,
		&i.LnPreimageHash,
		&i.LnInvoice,
		&i.ChainFundingTxid,
		&i.ChainRedeemTxid,
		&i.ChainAddress,
		&i.ChainPrivateKey,
		&i.ChainSwapTree,
	)
	return i, err
}

const updateSwap = `-- name: UpdateSwap :execrows
UPDATE swap
SET
    status = ?1,
    updated_at = ?2,
    funding_txid = ?3,
    redeem_txid = ?4,
    preimage = ?5,
    chain_funding_txid = ?6,
    chain_redeem_txid = ?7
WHERE id = ?8
`

type UpdateSwapParams struct {
	Status           int64
	UpdatedAt        sql.NullInt64
	FundingTxid      sql.NullString
	RedeemTxid       sql.NullString
	Preimage         sql.NullString
	ChainFundingTxid sql.NullString
	ChainRedeemTxid  sql.NullString
	ID               string
}

func (q *Queries) UpdateSwap(ctx context.Context, arg UpdateSwapParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSwap,
		arg.Status,
		arg.UpdatedAt,
		arg.FundingTxid,
		arg.RedeemTxid,
		arg.Preimage,
		arg.ChainFundingTxid,
		arg.ChainRedeemTxid,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
