// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package queries

import (
	"context"
	"database/sql"
)

const insertSwap = `-- name: InsertSwap :exec
INSERT INTO swap (
    id, from_currency, to_currency, amount, status, created_at, updated_at,
    vhtlc_script, funding_txid, redeem_txid, preimage,
    ln_preimage_hash, ln_invoice,
    chain_funding_txid, chain_redeem_txid, chain_address, chain_private_key,
    chain_destination_address, chain_server_public_key, chain_refund_locktime
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertSwapParams struct {
	ID                      string
	FromCurrency            string
	ToCurrency              string
	Amount                  int64
	Status                  int64
	CreatedAt               int64
	UpdatedAt               sql.NullInt64
	VhtlcScript             string
	FundingTxid             sql.NullString
	RedeemTxid              sql.NullString
	Preimage                sql.NullString
	LnPreimageHash          sql.NullString
	LnInvoice               sql.NullString
	ChainFundingTxid        sql.NullString
	ChainRedeemTxid         sql.NullString
	ChainAddress            sql.NullString
	ChainPrivateKey         sql.NullString
	ChainDestinationAddress sql.NullString
	ChainServerPublicKey    sql.NullString
	ChainRefundLocktime     sql.NullInt64
}

func (q *Queries) InsertSwap(ctx context.Context, arg InsertSwapParams) error {
	_, err := q.db.ExecContext(ctx, insertSwap,
		arg.ID,
		arg.FromCurrency,
		arg.ToCurrency,
		arg.Amount,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.VhtlcScript,
		arg.FundingTxid,
		arg.RedeemTxid,
		arg.Preimage,
		arg.LnPreimageHash,
		arg.LnInvoice,
		arg.ChainFundingTxid,
		arg.ChainRedeemTxid,
		arg.ChainAddress,
		arg.ChainPrivateKey,
		arg.ChainDestinationAddress,
		arg.ChainServerPublicKey,
		arg.ChainRefundLocktime,
	)
	return err
}

const selectAllSwaps = `-- name: SelectAllSwaps :many
SELECT id, from_currency, to_currency, amount, status, created_at, updated_at, vhtlc_script, funding_txid, redeem_txid, preimage, ln_preimage_hash, ln_invoice, chain_funding_txid, chain_redeem_txid, chain_address, chain_private_key, chain_destination_address, chain_server_public_key, chain_refund_locktime FROM swap
ORDER BY created_at ASC
`

func (q *Queries) SelectAllSwaps(ctx context.Context) ([]Swap, error) {
	rows, err := q.db.QueryContext(ctx, selectAllSwaps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Swap
	for rows.Next() {
		var i Swap
		if err := rows.Scan(
			&i.ID,
			&i.FromCurrency,
			&i.ToCurrency,
			&i.Amount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VhtlcScript,
			&i.FundingTxid,
			&i.RedeemTxid,
			&i.Preimage,
			&i.LnPreimageHash,
			&i.LnInvoice,
			&i.ChainFundingTxid,
			&i.ChainRedeemTxid,
			&i.ChainAddress,
			&i.ChainPrivateKey,
			&i.ChainDestinationAddress,
			&i.ChainServerPublicKey,
			&i.ChainRefundLocktime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectSwap = `-- name: SelectSwap :one
SELECT id, from_currency, to_currency, amount, status, created_at, updated_at, vhtlc_script, funding_txid, redeem_txid, preimage, ln_preimage_hash, ln_invoice, chain_funding_txid, chain_redeem_txid, chain_address, chain_private_key, chain_destination_address, chain_server_public_key, chain_refund_locktime FROM swap
WHERE id = ?1
`

func (q *Queries) SelectSwap(ctx context.Context, id string) (Swap, error) {
	row := q.db.QueryRowContext(ctx, selectSwap, id)
	var i Swap
	err := row.Scan(
		&i.ID,
		&i.FromCurrency,
		&i.ToCurrency,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VhtlcScript,
		&i.FundingTxid,
		&i.RedeemTxid,
		&i.Preimage,
		&i.LnPreimageHash,
		&i.LnInvoice,
		&i.ChainFundingTxid,
		&i.ChainRedeemTxid,
		&i.ChainAddress,
		&i.ChainPrivateKey,
		&i.ChainDestinationAddress,
		&i.ChainServerPublicKey,
		&i.ChainRefundLocktime,
	)
	return i, err
}

const selectSwapsByStatus = `-- name: SelectSwapsByStatus :many
SELECT id, from_currency, to_currency, amount, status, created_at, updated_at, vhtlc_script, funding_txid, redeem_txid, preimage, ln_preimage_hash, ln_invoice, chain_funding_txid, chain_redeem_txid, chain_address, chain_private_key, chain_destination_address, chain_server_public_key, chain_refund_locktime FROM swap
WHERE status = ?1
ORDER BY created_at ASC
`

func (q *Queries) SelectSwapsByStatus(ctx context.Context, status int64) ([]Swap, error) {
	rows, err := q.db.QueryContext(ctx, selectSwapsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Swap
	for rows.Next() {
		var i Swap
		if err := rows.Scan(
			&i.ID,
			&i.FromCurrency,
			&i.ToCurrency,
			&i.Amount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VhtlcScript,
			&i.FundingTxid,
			&i.RedeemTxid,
			&i.Preimage,
			&i.LnPreimageHash,
			&i.LnInvoice,
			&i.ChainFundingTxid,
			&i.ChainRedeemTxid,
			&i.ChainAddress,
			&i.ChainPrivateKey,
			&i.ChainDestinationAddress,
			&i.ChainServerPublicKey,
			&i.ChainRefundLocktime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSwap = `-- name: UpdateSwap :execrows
UPDATE swap
SET
    status = ?1,
    updated_at = ?2,
    funding_txid = ?3,
    redeem_txid = ?4,
    preimage = ?5,
    chain_funding_txid = ?6,
    chain_redeem_txid = ?7
WHERE id = ?8
`

type UpdateSwapParams struct {
	Status           int64
	UpdatedAt        sql.NullInt64
	FundingTxid      sql.NullString
	RedeemTxid       sql.NullString
	Preimage         sql.NullString
	ChainFundingTxid sql.NullString
	ChainRedeemTxid  sql.NullString
	ID               string
}

func (q *Queries) UpdateSwap(ctx context.Context, arg UpdateSwapParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSwap,
		arg.Status,
		arg.UpdatedAt,
		arg.FundingTxid,
		arg.RedeemTxid,
		arg.Preimage,
		arg.ChainFundingTxid,
		arg.ChainRedeemTxid,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
