/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Outpoint type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Outpoint{}

// Outpoint struct for Outpoint
type Outpoint struct {
		Txid *string `json:"txid,omitempty"`
		Vout *int32 `json:"vout,omitempty"`
}

// NewOutpoint instantiates a new Outpoint object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOutpoint() *Outpoint {
	this := Outpoint{}
	return &this
}

// NewOutpointWithDefaults instantiates a new Outpoint object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOutpointWithDefaults() *Outpoint {
	this := Outpoint{}
	return &this
}

// GetTxid returns the Txid field value if set, zero value otherwise.
func (o *Outpoint) GetTxid() string {
	if o == nil || IsNil(o.Txid) {
		var ret string
		return ret
	}
	return *o.Txid
}

// GetTxidOk returns a tuple with the Txid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Outpoint) GetTxidOk() (*string, bool) {
	if o == nil || IsNil(o.Txid) {
		return nil, false
	}
	return o.Txid, true
}

// HasTxid returns a boolean if a field has been set.
func (o *Outpoint) HasTxid() bool {
	if o != nil && !IsNil(o.Txid) {
		return true
	}

	return false
}

// SetTxid gets a reference to the given string and assigns it to the Txid field.
func (o *Outpoint) SetTxid(v string) {
	o.Txid = &v
}

// GetVout returns the Vout field value if set, zero value otherwise.
func (o *Outpoint) GetVout() int32 {
	if o == nil || IsNil(o.Vout) {
		var ret int32
		return ret
	}
	return *o.Vout
}

// GetVoutOk returns a tuple with the Vout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Outpoint) GetVoutOk() (*int32, bool) {
	if o == nil || IsNil(o.Vout) {
		return nil, false
	}
	return o.Vout, true
}

// HasVout returns a boolean if a field has been set.
func (o *Outpoint) HasVout() bool {
	if o != nil && !IsNil(o.Vout) {
		return true
	}

	return false
}

// SetVout gets a reference to the given int32 and assigns it to the Vout field.
func (o *Outpoint) SetVout(v int32) {
	o.Vout = &v
}

func (o Outpoint) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Outpoint) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Txid) {
		toSerialize["txid"] = o.Txid
	}
	if !IsNil(o.Vout) {
		toSerialize["vout"] = o.Vout
	}
	return toSerialize, nil
}

type NullableOutpoint struct {
	value *Outpoint
	isSet bool
}

func (v NullableOutpoint) Get() *Outpoint {
	return v.value
}

func (v *NullableOutpoint) Set(val *Outpoint) {
	v.value = val
	v.isSet = true
}

func (v NullableOutpoint) IsSet() bool {
	return v.isSet
}

func (v *NullableOutpoint) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutpoint(val *Outpoint) *NullableOutpoint {
	return &NullableOutpoint{value: val, isSet: true}
}

func (v NullableOutpoint) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutpoint) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


