/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PendingTx type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PendingTx{}

// PendingTx struct for PendingTx
type PendingTx struct {
		ArkTxid *string `json:"arkTxid,omitempty"`
		FinalArkTx *string `json:"finalArkTx,omitempty"`
		SignedCheckpointTxs []string `json:"signedCheckpointTxs,omitempty"`
}

// NewPendingTx instantiates a new PendingTx object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPendingTx() *PendingTx {
	this := PendingTx{}
	return &this
}

// NewPendingTxWithDefaults instantiates a new PendingTx object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPendingTxWithDefaults() *PendingTx {
	this := PendingTx{}
	return &this
}

// GetArkTxid returns the ArkTxid field value if set, zero value otherwise.
func (o *PendingTx) GetArkTxid() string {
	if o == nil || IsNil(o.ArkTxid) {
		var ret string
		return ret
	}
	return *o.ArkTxid
}

// GetArkTxidOk returns a tuple with the ArkTxid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PendingTx) GetArkTxidOk() (*string, bool) {
	if o == nil || IsNil(o.ArkTxid) {
		return nil, false
	}
	return o.ArkTxid, true
}

// HasArkTxid returns a boolean if a field has been set.
func (o *PendingTx) HasArkTxid() bool {
	if o != nil && !IsNil(o.ArkTxid) {
		return true
	}

	return false
}

// SetArkTxid gets a reference to the given string and assigns it to the ArkTxid field.
func (o *PendingTx) SetArkTxid(v string) {
	o.ArkTxid = &v
}

// GetFinalArkTx returns the FinalArkTx field value if set, zero value otherwise.
func (o *PendingTx) GetFinalArkTx() string {
	if o == nil || IsNil(o.FinalArkTx) {
		var ret string
		return ret
	}
	return *o.FinalArkTx
}

// GetFinalArkTxOk returns a tuple with the FinalArkTx field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PendingTx) GetFinalArkTxOk() (*string, bool) {
	if o == nil || IsNil(o.FinalArkTx) {
		return nil, false
	}
	return o.FinalArkTx, true
}

// HasFinalArkTx returns a boolean if a field has been set.
func (o *PendingTx) HasFinalArkTx() bool {
	if o != nil && !IsNil(o.FinalArkTx) {
		return true
	}

	return false
}

// SetFinalArkTx gets a reference to the given string and assigns it to the FinalArkTx field.
func (o *PendingTx) SetFinalArkTx(v string) {
	o.FinalArkTx = &v
}

// GetSignedCheckpointTxs returns the SignedCheckpointTxs field value if set, zero value otherwise.
func (o *PendingTx) GetSignedCheckpointTxs() []string {
	if o == nil || IsNil(o.SignedCheckpointTxs) {
		var ret []string
		return ret
	}
	return o.SignedCheckpointTxs
}

// GetSignedCheckpointTxsOk returns a tuple with the SignedCheckpointTxs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PendingTx) GetSignedCheckpointTxsOk() ([]string, bool) {
	if o == nil || IsNil(o.SignedCheckpointTxs) {
		return nil, false
	}
	return o.SignedCheckpointTxs, true
}

// HasSignedCheckpointTxs returns a boolean if a field has been set.
func (o *PendingTx) HasSignedCheckpointTxs() bool {
	if o != nil && !IsNil(o.SignedCheckpointTxs) {
		return true
	}

	return false
}

// SetSignedCheckpointTxs gets a reference to the given []string and assigns it to the SignedCheckpointTxs field.
func (o *PendingTx) SetSignedCheckpointTxs(v []string) {
	o.SignedCheckpointTxs = v
}

func (o PendingTx) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PendingTx) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ArkTxid) {
		toSerialize["arkTxid"] = o.ArkTxid
	}
	if !IsNil(o.FinalArkTx) {
		toSerialize["finalArkTx"] = o.FinalArkTx
	}
	if !IsNil(o.SignedCheckpointTxs) {
		toSerialize["signedCheckpointTxs"] = o.SignedCheckpointTxs
	}
	return toSerialize, nil
}

type NullablePendingTx struct {
	value *PendingTx
	isSet bool
}

func (v NullablePendingTx) Get() *PendingTx {
	return v.value
}

func (v *NullablePendingTx) Set(val *PendingTx) {
	v.value = val
	v.isSet = true
}

func (v NullablePendingTx) IsSet() bool {
	return v.isSet
}

func (v *NullablePendingTx) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePendingTx(val *PendingTx) *NullablePendingTx {
	return &NullablePendingTx{value: val, isSet: true}
}

func (v NullablePendingTx) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePendingTx) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


