/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetIntentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetIntentRequest{}

// GetIntentRequest struct for GetIntentRequest
type GetIntentRequest struct {
		Intent *Intent `json:"intent,omitempty"`
		Txid *string `json:"txid,omitempty"`
}

// NewGetIntentRequest instantiates a new GetIntentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetIntentRequest() *GetIntentRequest {
	this := GetIntentRequest{}
	return &this
}

// NewGetIntentRequestWithDefaults instantiates a new GetIntentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetIntentRequestWithDefaults() *GetIntentRequest {
	this := GetIntentRequest{}
	return &this
}

// GetIntent returns the Intent field value if set, zero value otherwise.
func (o *GetIntentRequest) GetIntent() Intent {
	if o == nil || IsNil(o.Intent) {
		var ret Intent
		return ret
	}
	return *o.Intent
}

// GetIntentOk returns a tuple with the Intent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIntentRequest) GetIntentOk() (*Intent, bool) {
	if o == nil || IsNil(o.Intent) {
		return nil, false
	}
	return o.Intent, true
}

// HasIntent returns a boolean if a field has been set.
func (o *GetIntentRequest) HasIntent() bool {
	if o != nil && !IsNil(o.Intent) {
		return true
	}

	return false
}

// SetIntent gets a reference to the given Intent and assigns it to the Intent field.
func (o *GetIntentRequest) SetIntent(v Intent) {
	o.Intent = &v
}

// GetTxid returns the Txid field value if set, zero value otherwise.
func (o *GetIntentRequest) GetTxid() string {
	if o == nil || IsNil(o.Txid) {
		var ret string
		return ret
	}
	return *o.Txid
}

// GetTxidOk returns a tuple with the Txid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIntentRequest) GetTxidOk() (*string, bool) {
	if o == nil || IsNil(o.Txid) {
		return nil, false
	}
	return o.Txid, true
}

// HasTxid returns a boolean if a field has been set.
func (o *GetIntentRequest) HasTxid() bool {
	if o != nil && !IsNil(o.Txid) {
		return true
	}

	return false
}

// SetTxid gets a reference to the given string and assigns it to the Txid field.
func (o *GetIntentRequest) SetTxid(v string) {
	o.Txid = &v
}

func (o GetIntentRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetIntentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Intent) {
		toSerialize["intent"] = o.Intent
	}
	if !IsNil(o.Txid) {
		toSerialize["txid"] = o.Txid
	}
	return toSerialize, nil
}

type NullableGetIntentRequest struct {
	value *GetIntentRequest
	isSet bool
}

func (v NullableGetIntentRequest) Get() *GetIntentRequest {
	return v.value
}

func (v *NullableGetIntentRequest) Set(val *GetIntentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetIntentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetIntentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetIntentRequest(val *GetIntentRequest) *NullableGetIntentRequest {
	return &NullableGetIntentRequest{value: val, isSet: true}
}

func (v NullableGetIntentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetIntentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


