/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ConfirmRegistrationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfirmRegistrationRequest{}

// ConfirmRegistrationRequest struct for ConfirmRegistrationRequest
type ConfirmRegistrationRequest struct {
	IntentId *string `json:"intentId,omitempty"`
}

// NewConfirmRegistrationRequest instantiates a new ConfirmRegistrationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfirmRegistrationRequest() *ConfirmRegistrationRequest {
	this := ConfirmRegistrationRequest{}
	return &this
}

// NewConfirmRegistrationRequestWithDefaults instantiates a new ConfirmRegistrationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfirmRegistrationRequestWithDefaults() *ConfirmRegistrationRequest {
	this := ConfirmRegistrationRequest{}
	return &this
}

// GetIntentId returns the IntentId field value if set, zero value otherwise.
func (o *ConfirmRegistrationRequest) GetIntentId() string {
	if o == nil || IsNil(o.IntentId) {
		var ret string
		return ret
	}
	return *o.IntentId
}

// GetIntentIdOk returns a tuple with the IntentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfirmRegistrationRequest) GetIntentIdOk() (*string, bool) {
	if o == nil || IsNil(o.IntentId) {
		return nil, false
	}
	return o.IntentId, true
}

// HasIntentId returns a boolean if a field has been set.
func (o *ConfirmRegistrationRequest) HasIntentId() bool {
	if o != nil && !IsNil(o.IntentId) {
		return true
	}

	return false
}

// SetIntentId gets a reference to the given string and assigns it to the IntentId field.
func (o *ConfirmRegistrationRequest) SetIntentId(v string) {
	o.IntentId = &v
}

func (o ConfirmRegistrationRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfirmRegistrationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IntentId) {
		toSerialize["intentId"] = o.IntentId
	}
	return toSerialize, nil
}

type NullableConfirmRegistrationRequest struct {
	value *ConfirmRegistrationRequest
	isSet bool
}

func (v NullableConfirmRegistrationRequest) Get() *ConfirmRegistrationRequest {
	return v.value
}

func (v *NullableConfirmRegistrationRequest) Set(val *ConfirmRegistrationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableConfirmRegistrationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableConfirmRegistrationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfirmRegistrationRequest(val *ConfirmRegistrationRequest) *NullableConfirmRegistrationRequest {
	return &NullableConfirmRegistrationRequest{value: val, isSet: true}
}

func (v NullableConfirmRegistrationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfirmRegistrationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


