/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TreeNoncesAggregatedEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TreeNoncesAggregatedEvent{}

// TreeNoncesAggregatedEvent struct for TreeNoncesAggregatedEvent
type TreeNoncesAggregatedEvent struct {
		Id *string `json:"id,omitempty"`
		TreeNonces map[string]string `json:"treeNonces,omitempty"`
}

// NewTreeNoncesAggregatedEvent instantiates a new TreeNoncesAggregatedEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTreeNoncesAggregatedEvent() *TreeNoncesAggregatedEvent {
	this := TreeNoncesAggregatedEvent{}
	return &this
}

// NewTreeNoncesAggregatedEventWithDefaults instantiates a new TreeNoncesAggregatedEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTreeNoncesAggregatedEventWithDefaults() *TreeNoncesAggregatedEvent {
	this := TreeNoncesAggregatedEvent{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *TreeNoncesAggregatedEvent) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TreeNoncesAggregatedEvent) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *TreeNoncesAggregatedEvent) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *TreeNoncesAggregatedEvent) SetId(v string) {
	o.Id = &v
}

// GetTreeNonces returns the TreeNonces field value if set, zero value otherwise.
func (o *TreeNoncesAggregatedEvent) GetTreeNonces() map[string]string {
	if o == nil || IsNil(o.TreeNonces) {
		var ret map[string]string
		return ret
	}
	return o.TreeNonces
}

// GetTreeNoncesOk returns a tuple with the TreeNonces field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TreeNoncesAggregatedEvent) GetTreeNoncesOk() (map[string]string, bool) {
	if o == nil || IsNil(o.TreeNonces) {
		return map[string]string{}, false
	}
	return o.TreeNonces, true
}

// HasTreeNonces returns a boolean if a field has been set.
func (o *TreeNoncesAggregatedEvent) HasTreeNonces() bool {
	if o != nil && !IsNil(o.TreeNonces) {
		return true
	}

	return false
}

// SetTreeNonces gets a reference to the given map[string]string and assigns it to the TreeNonces field.
func (o *TreeNoncesAggregatedEvent) SetTreeNonces(v map[string]string) {
	o.TreeNonces = v
}

func (o TreeNoncesAggregatedEvent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TreeNoncesAggregatedEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.TreeNonces) {
		toSerialize["treeNonces"] = o.TreeNonces
	}
	return toSerialize, nil
}

type NullableTreeNoncesAggregatedEvent struct {
	value *TreeNoncesAggregatedEvent
	isSet bool
}

func (v NullableTreeNoncesAggregatedEvent) Get() *TreeNoncesAggregatedEvent {
	return v.value
}

func (v *NullableTreeNoncesAggregatedEvent) Set(val *TreeNoncesAggregatedEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableTreeNoncesAggregatedEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableTreeNoncesAggregatedEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTreeNoncesAggregatedEvent(val *TreeNoncesAggregatedEvent) *NullableTreeNoncesAggregatedEvent {
	return &NullableTreeNoncesAggregatedEvent{value: val, isSet: true}
}

func (v NullableTreeNoncesAggregatedEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTreeNoncesAggregatedEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


