/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetIntentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetIntentResponse{}

// GetIntentResponse struct for GetIntentResponse
type GetIntentResponse struct {
		Intent *Intent `json:"intent,omitempty"`
}

// NewGetIntentResponse instantiates a new GetIntentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetIntentResponse() *GetIntentResponse {
	this := GetIntentResponse{}
	return &this
}

// NewGetIntentResponseWithDefaults instantiates a new GetIntentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetIntentResponseWithDefaults() *GetIntentResponse {
	this := GetIntentResponse{}
	return &this
}

// GetIntent returns the Intent field value if set, zero value otherwise.
func (o *GetIntentResponse) GetIntent() Intent {
	if o == nil || IsNil(o.Intent) {
		var ret Intent
		return ret
	}
	return *o.Intent
}

// GetIntentOk returns a tuple with the Intent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIntentResponse) GetIntentOk() (*Intent, bool) {
	if o == nil || IsNil(o.Intent) {
		return nil, false
	}
	return o.Intent, true
}

// HasIntent returns a boolean if a field has been set.
func (o *GetIntentResponse) HasIntent() bool {
	if o != nil && !IsNil(o.Intent) {
		return true
	}

	return false
}

// SetIntent gets a reference to the given Intent and assigns it to the Intent field.
func (o *GetIntentResponse) SetIntent(v Intent) {
	o.Intent = &v
}

func (o GetIntentResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetIntentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Intent) {
		toSerialize["intent"] = o.Intent
	}
	return toSerialize, nil
}

type NullableGetIntentResponse struct {
	value *GetIntentResponse
	isSet bool
}

func (v NullableGetIntentResponse) Get() *GetIntentResponse {
	return v.value
}

func (v *NullableGetIntentResponse) Set(val *GetIntentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetIntentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetIntentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetIntentResponse(val *GetIntentResponse) *NullableGetIntentResponse {
	return &NullableGetIntentResponse{value: val, isSet: true}
}

func (v NullableGetIntentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetIntentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


