/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the FeeInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FeeInfo{}

// FeeInfo struct for FeeInfo
type FeeInfo struct {
		IntentFee *IntentFeeInfo `json:"intentFee,omitempty"`
		TxFeeRate *string `json:"txFeeRate,omitempty"`
}

// NewFeeInfo instantiates a new FeeInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFeeInfo() *FeeInfo {
	this := FeeInfo{}
	return &this
}

// NewFeeInfoWithDefaults instantiates a new FeeInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFeeInfoWithDefaults() *FeeInfo {
	this := FeeInfo{}
	return &this
}

// GetIntentFee returns the IntentFee field value if set, zero value otherwise.
func (o *FeeInfo) GetIntentFee() IntentFeeInfo {
	if o == nil || IsNil(o.IntentFee) {
		var ret IntentFeeInfo
		return ret
	}
	return *o.IntentFee
}

// GetIntentFeeOk returns a tuple with the IntentFee field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeeInfo) GetIntentFeeOk() (*IntentFeeInfo, bool) {
	if o == nil || IsNil(o.IntentFee) {
		return nil, false
	}
	return o.IntentFee, true
}

// HasIntentFee returns a boolean if a field has been set.
func (o *FeeInfo) HasIntentFee() bool {
	if o != nil && !IsNil(o.IntentFee) {
		return true
	}

	return false
}

// SetIntentFee gets a reference to the given IntentFeeInfo and assigns it to the IntentFee field.
func (o *FeeInfo) SetIntentFee(v IntentFeeInfo) {
	o.IntentFee = &v
}

// GetTxFeeRate returns the TxFeeRate field value if set, zero value otherwise.
func (o *FeeInfo) GetTxFeeRate() string {
	if o == nil || IsNil(o.TxFeeRate) {
		var ret string
		return ret
	}
	return *o.TxFeeRate
}

// GetTxFeeRateOk returns a tuple with the TxFeeRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeeInfo) GetTxFeeRateOk() (*string, bool) {
	if o == nil || IsNil(o.TxFeeRate) {
		return nil, false
	}
	return o.TxFeeRate, true
}

// HasTxFeeRate returns a boolean if a field has been set.
func (o *FeeInfo) HasTxFeeRate() bool {
	if o != nil && !IsNil(o.TxFeeRate) {
		return true
	}

	return false
}

// SetTxFeeRate gets a reference to the given string and assigns it to the TxFeeRate field.
func (o *FeeInfo) SetTxFeeRate(v string) {
	o.TxFeeRate = &v
}

func (o FeeInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FeeInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IntentFee) {
		toSerialize["intentFee"] = o.IntentFee
	}
	if !IsNil(o.TxFeeRate) {
		toSerialize["txFeeRate"] = o.TxFeeRate
	}
	return toSerialize, nil
}

type NullableFeeInfo struct {
	value *FeeInfo
	isSet bool
}

func (v NullableFeeInfo) Get() *FeeInfo {
	return v.value
}

func (v *NullableFeeInfo) Set(val *FeeInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableFeeInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableFeeInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFeeInfo(val *FeeInfo) *NullableFeeInfo {
	return &NullableFeeInfo{value: val, isSet: true}
}

func (v NullableFeeInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFeeInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


