/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetPendingTxRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetPendingTxRequest{}

// GetPendingTxRequest struct for GetPendingTxRequest
type GetPendingTxRequest struct {
		Intent *Intent `json:"intent,omitempty"`
}

// NewGetPendingTxRequest instantiates a new GetPendingTxRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPendingTxRequest() *GetPendingTxRequest {
	this := GetPendingTxRequest{}
	return &this
}

// NewGetPendingTxRequestWithDefaults instantiates a new GetPendingTxRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPendingTxRequestWithDefaults() *GetPendingTxRequest {
	this := GetPendingTxRequest{}
	return &this
}

// GetIntent returns the Intent field value if set, zero value otherwise.
func (o *GetPendingTxRequest) GetIntent() Intent {
	if o == nil || IsNil(o.Intent) {
		var ret Intent
		return ret
	}
	return *o.Intent
}

// GetIntentOk returns a tuple with the Intent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPendingTxRequest) GetIntentOk() (*Intent, bool) {
	if o == nil || IsNil(o.Intent) {
		return nil, false
	}
	return o.Intent, true
}

// HasIntent returns a boolean if a field has been set.
func (o *GetPendingTxRequest) HasIntent() bool {
	if o != nil && !IsNil(o.Intent) {
		return true
	}

	return false
}

// SetIntent gets a reference to the given Intent and assigns it to the Intent field.
func (o *GetPendingTxRequest) SetIntent(v Intent) {
	o.Intent = &v
}

func (o GetPendingTxRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetPendingTxRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Intent) {
		toSerialize["intent"] = o.Intent
	}
	return toSerialize, nil
}

type NullableGetPendingTxRequest struct {
	value *GetPendingTxRequest
	isSet bool
}

func (v NullableGetPendingTxRequest) Get() *GetPendingTxRequest {
	return v.value
}

func (v *NullableGetPendingTxRequest) Set(val *GetPendingTxRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPendingTxRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPendingTxRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPendingTxRequest(val *GetPendingTxRequest) *NullableGetPendingTxRequest {
	return &NullableGetPendingTxRequest{value: val, isSet: true}
}

func (v NullableGetPendingTxRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPendingTxRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


