/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SubmitTreeSignaturesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubmitTreeSignaturesRequest{}

// SubmitTreeSignaturesRequest struct for SubmitTreeSignaturesRequest
type SubmitTreeSignaturesRequest struct {
		BatchId *string `json:"batchId,omitempty"`
		Pubkey *string `json:"pubkey,omitempty"`
		TreeSignatures *string `json:"treeSignatures,omitempty"`
}

// NewSubmitTreeSignaturesRequest instantiates a new SubmitTreeSignaturesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubmitTreeSignaturesRequest() *SubmitTreeSignaturesRequest {
	this := SubmitTreeSignaturesRequest{}
	return &this
}

// NewSubmitTreeSignaturesRequestWithDefaults instantiates a new SubmitTreeSignaturesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubmitTreeSignaturesRequestWithDefaults() *SubmitTreeSignaturesRequest {
	this := SubmitTreeSignaturesRequest{}
	return &this
}

// GetBatchId returns the BatchId field value if set, zero value otherwise.
func (o *SubmitTreeSignaturesRequest) GetBatchId() string {
	if o == nil || IsNil(o.BatchId) {
		var ret string
		return ret
	}
	return *o.BatchId
}

// GetBatchIdOk returns a tuple with the BatchId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmitTreeSignaturesRequest) GetBatchIdOk() (*string, bool) {
	if o == nil || IsNil(o.BatchId) {
		return nil, false
	}
	return o.BatchId, true
}

// HasBatchId returns a boolean if a field has been set.
func (o *SubmitTreeSignaturesRequest) HasBatchId() bool {
	if o != nil && !IsNil(o.BatchId) {
		return true
	}

	return false
}

// SetBatchId gets a reference to the given string and assigns it to the BatchId field.
func (o *SubmitTreeSignaturesRequest) SetBatchId(v string) {
	o.BatchId = &v
}

// GetPubkey returns the Pubkey field value if set, zero value otherwise.
func (o *SubmitTreeSignaturesRequest) GetPubkey() string {
	if o == nil || IsNil(o.Pubkey) {
		var ret string
		return ret
	}
	return *o.Pubkey
}

// GetPubkeyOk returns a tuple with the Pubkey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmitTreeSignaturesRequest) GetPubkeyOk() (*string, bool) {
	if o == nil || IsNil(o.Pubkey) {
		return nil, false
	}
	return o.Pubkey, true
}

// HasPubkey returns a boolean if a field has been set.
func (o *SubmitTreeSignaturesRequest) HasPubkey() bool {
	if o != nil && !IsNil(o.Pubkey) {
		return true
	}

	return false
}

// SetPubkey gets a reference to the given string and assigns it to the Pubkey field.
func (o *SubmitTreeSignaturesRequest) SetPubkey(v string) {
	o.Pubkey = &v
}

// GetTreeSignatures returns the TreeSignatures field value if set, zero value otherwise.
func (o *SubmitTreeSignaturesRequest) GetTreeSignatures() string {
	if o == nil || IsNil(o.TreeSignatures) {
		var ret string
		return ret
	}
	return *o.TreeSignatures
}

// GetTreeSignaturesOk returns a tuple with the TreeSignatures field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmitTreeSignaturesRequest) GetTreeSignaturesOk() (*string, bool) {
	if o == nil || IsNil(o.TreeSignatures) {
		return nil, false
	}
	return o.TreeSignatures, true
}

// HasTreeSignatures returns a boolean if a field has been set.
func (o *SubmitTreeSignaturesRequest) HasTreeSignatures() bool {
	if o != nil && !IsNil(o.TreeSignatures) {
		return true
	}

	return false
}

// SetTreeSignatures gets a reference to the given string and assigns it to the TreeSignatures field.
func (o *SubmitTreeSignaturesRequest) SetTreeSignatures(v string) {
	o.TreeSignatures = &v
}

func (o SubmitTreeSignaturesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubmitTreeSignaturesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BatchId) {
		toSerialize["batchId"] = o.BatchId
	}
	if !IsNil(o.Pubkey) {
		toSerialize["pubkey"] = o.Pubkey
	}
	if !IsNil(o.TreeSignatures) {
		toSerialize["treeSignatures"] = o.TreeSignatures
	}
	return toSerialize, nil
}

type NullableSubmitTreeSignaturesRequest struct {
	value *SubmitTreeSignaturesRequest
	isSet bool
}

func (v NullableSubmitTreeSignaturesRequest) Get() *SubmitTreeSignaturesRequest {
	return v.value
}

func (v *NullableSubmitTreeSignaturesRequest) Set(val *SubmitTreeSignaturesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSubmitTreeSignaturesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSubmitTreeSignaturesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubmitTreeSignaturesRequest(val *SubmitTreeSignaturesRequest) *NullableSubmitTreeSignaturesRequest {
	return &NullableSubmitTreeSignaturesRequest{value: val, isSet: true}
}

func (v NullableSubmitTreeSignaturesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubmitTreeSignaturesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


