// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1DeleteIntentRequest v1 delete intent request
//
// swagger:model v1DeleteIntentRequest
type V1DeleteIntentRequest struct {

	// an intent proof that includes any of the inputs of the intent to be deleted to prove the
	// ownership of that intent.
	Intent *V1Intent `json:"intent,omitempty"`
}

// Validate validates this v1 delete intent request
func (m *V1DeleteIntentRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateIntent(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1DeleteIntentRequest) validateIntent(formats strfmt.Registry) error {
	if swag.IsZero(m.Intent) { // not required
		return nil
	}

	if m.Intent != nil {
		if err := m.Intent.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("intent")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("intent")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this v1 delete intent request based on the context it is used
func (m *V1DeleteIntentRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateIntent(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1DeleteIntentRequest) contextValidateIntent(ctx context.Context, formats strfmt.Registry) error {

	if m.Intent != nil {

		if swag.IsZero(m.Intent) { // not required
			return nil
		}

		if err := m.Intent.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("intent")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("intent")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1DeleteIntentRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1DeleteIntentRequest) UnmarshalBinary(b []byte) error {
	var res V1DeleteIntentRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
