// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1Intent v1 intent
//
// swagger:model v1Intent
type V1Intent struct {

	// message
	Message string `json:"message,omitempty"`

	// proof
	Proof string `json:"proof,omitempty"`
}

// Validate validates this v1 intent
func (m *V1Intent) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 intent based on context it is used
func (m *V1Intent) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1Intent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1Intent) UnmarshalBinary(b []byte) error {
	var res V1Intent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
