// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1TreeNoncesEvent v1 tree nonces event
//
// swagger:model v1TreeNoncesEvent
type V1TreeNoncesEvent struct {

	// id
	ID string `json:"id,omitempty"`

	// pubkey -> musig2 public nonce
	Nonces map[string]string `json:"nonces,omitempty"`

	// topic
	Topic []string `json:"topic"`

	// txid
	Txid string `json:"txid,omitempty"`
}

// Validate validates this v1 tree nonces event
func (m *V1TreeNoncesEvent) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 tree nonces event based on context it is used
func (m *V1TreeNoncesEvent) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1TreeNoncesEvent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1TreeNoncesEvent) UnmarshalBinary(b []byte) error {
	var res V1TreeNoncesEvent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
