// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package queries

import (
	"context"
	"database/sql"
	"strings"
)

const cleanAssetVtxos = `-- name: CleanAssetVtxos :exec
DELETE FROM asset_vtxo
`

func (q *Queries) CleanAssetVtxos(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanAssetVtxos)
	return err
}

const cleanAssets = `-- name: CleanAssets :exec
DELETE FROM asset
`

func (q *Queries) CleanAssets(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanAssets)
	return err
}

const cleanContracts = `-- name: CleanContracts :exec
DELETE FROM contract
`

func (q *Queries) CleanContracts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanContracts)
	return err
}

const cleanTxs = `-- name: CleanTxs :exec
DELETE FROM tx
`

func (q *Queries) CleanTxs(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanTxs)
	return err
}

const cleanUtxos = `-- name: CleanUtxos :exec
DELETE FROM utxo
`

func (q *Queries) CleanUtxos(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanUtxos)
	return err
}

const cleanVtxos = `-- name: CleanVtxos :exec
DELETE FROM vtxo
`

func (q *Queries) CleanVtxos(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanVtxos)
	return err
}

const deleteUtxo = `-- name: DeleteUtxo :exec
DELETE FROM utxo
WHERE txid = ?1 AND vout = ?2
`

type DeleteUtxoParams struct {
	Txid string
	Vout int64
}

func (q *Queries) DeleteUtxo(ctx context.Context, arg DeleteUtxoParams) error {
	_, err := q.db.ExecContext(ctx, deleteUtxo, arg.Txid, arg.Vout)
	return err
}

const insertAssetVtxo = `-- name: InsertAssetVtxo :exec
INSERT INTO asset_vtxo (vtxo_txid, vtxo_vout, asset_id, amount) VALUES (?, ?, ?, ?)
`

type InsertAssetVtxoParams struct {
	VtxoTxid string
	VtxoVout int64
	AssetID  string
	Amount   int64
}

func (q *Queries) InsertAssetVtxo(ctx context.Context, arg InsertAssetVtxoParams) error {
	_, err := q.db.ExecContext(ctx, insertAssetVtxo,
		arg.VtxoTxid,
		arg.VtxoVout,
		arg.AssetID,
		arg.Amount,
	)
	return err
}

const insertContract = `-- name: InsertContract :exec
INSERT INTO contract (
    script, type, label, address, is_onchain, state, created_at, owner_key_index, owner_key, signer_key, exit_delay, extra_params, metadata
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertContractParams struct {
	Script        string
	Type          string
	Label         sql.NullString
	Address       string
	IsOnchain     bool
	State         string
	CreatedAt     int64
	OwnerKeyIndex int64
	OwnerKey      string
	SignerKey     string
	ExitDelay     int64
	ExtraParams   sql.NullString
	Metadata      sql.NullString
}

func (q *Queries) InsertContract(ctx context.Context, arg InsertContractParams) error {
	_, err := q.db.ExecContext(ctx, insertContract,
		arg.Script,
		arg.Type,
		arg.Label,
		arg.Address,
		arg.IsOnchain,
		arg.State,
		arg.CreatedAt,
		arg.OwnerKeyIndex,
		arg.OwnerKey,
		arg.SignerKey,
		arg.ExitDelay,
		arg.ExtraParams,
		arg.Metadata,
	)
	return err
}

const insertTx = `-- name: InsertTx :exec
INSERT INTO tx (
    txid, txid_type, amount, type, created_at, hex, settled_by, settled, asset_packet
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertTxParams struct {
	Txid        string
	TxidType    string
	Amount      int64
	Type        string
	CreatedAt   int64
	Hex         sql.NullString
	SettledBy   sql.NullString
	Settled     bool
	AssetPacket sql.NullString
}

func (q *Queries) InsertTx(ctx context.Context, arg InsertTxParams) error {
	_, err := q.db.ExecContext(ctx, insertTx,
		arg.Txid,
		arg.TxidType,
		arg.Amount,
		arg.Type,
		arg.CreatedAt,
		arg.Hex,
		arg.SettledBy,
		arg.Settled,
		arg.AssetPacket,
	)
	return err
}

const insertUtxo = `-- name: InsertUtxo :exec
INSERT INTO utxo (
    txid, vout, script, amount, spent_by, spent, tapscripts, spendable_at, created_at, delay_value, delay_type, tx
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertUtxoParams struct {
	Txid        string
	Vout        int64
	Script      string
	Amount      int64
	SpentBy     sql.NullString
	Spent       bool
	Tapscripts  sql.NullString
	SpendableAt sql.NullInt64
	CreatedAt   sql.NullInt64
	DelayValue  sql.NullInt64
	DelayType   sql.NullString
	Tx          sql.NullString
}

func (q *Queries) InsertUtxo(ctx context.Context, arg InsertUtxoParams) error {
	_, err := q.db.ExecContext(ctx, insertUtxo,
		arg.Txid,
		arg.Vout,
		arg.Script,
		arg.Amount,
		arg.SpentBy,
		arg.Spent,
		arg.Tapscripts,
		arg.SpendableAt,
		arg.CreatedAt,
		arg.DelayValue,
		arg.DelayType,
		arg.Tx,
	)
	return err
}

const insertVtxo = `-- name: InsertVtxo :exec
INSERT INTO vtxo (
    txid, vout, script, amount, commitment_txids, spent_by, spent, preconfirmed, expires_at, created_at, swept, unrolled, settled_by, ark_txid
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertVtxoParams struct {
	Txid            string
	Vout            int64
	Script          string
	Amount          int64
	CommitmentTxids string
	SpentBy         sql.NullString
	Spent           bool
	Preconfirmed    bool
	ExpiresAt       int64
	CreatedAt       int64
	Swept           bool
	Unrolled        bool
	SettledBy       sql.NullString
	ArkTxid         sql.NullString
}

func (q *Queries) InsertVtxo(ctx context.Context, arg InsertVtxoParams) error {
	_, err := q.db.ExecContext(ctx, insertVtxo,
		arg.Txid,
		arg.Vout,
		arg.Script,
		arg.Amount,
		arg.CommitmentTxids,
		arg.SpentBy,
		arg.Spent,
		arg.Preconfirmed,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.Swept,
		arg.Unrolled,
		arg.SettledBy,
		arg.ArkTxid,
	)
	return err
}

const replaceTx = `-- name: ReplaceTx :exec
UPDATE tx
SET    txid       = ?1,
       txid_type  = ?2,
       amount     = ?3,
       type       = ?4,
       settled_by    = ?5,
       settled        = CASE WHEN ?5 IS NOT NULL THEN TRUE ELSE FALSE END,
       created_at = ?6,
       hex        = ?7
WHERE  txid = ?8
`

type ReplaceTxParams struct {
	NewTxid   string
	TxidType  string
	Amount    int64
	Type      string
	SettledBy sql.NullString
	CreatedAt int64
	Hex       sql.NullString
	OldTxid   string
}

func (q *Queries) ReplaceTx(ctx context.Context, arg ReplaceTxParams) error {
	_, err := q.db.ExecContext(ctx, replaceTx,
		arg.NewTxid,
		arg.TxidType,
		arg.Amount,
		arg.Type,
		arg.SettledBy,
		arg.CreatedAt,
		arg.Hex,
		arg.OldTxid,
	)
	return err
}

const selectAllContracts = `-- name: SelectAllContracts :many
SELECT script, type, label, address, state, created_at, owner_key_index, owner_key, signer_key, exit_delay, is_onchain, extra_params, metadata FROM contract WHERE is_onchain = ?1
`

func (q *Queries) SelectAllContracts(ctx context.Context, isOnchain bool) ([]Contract, error) {
	rows, err := q.db.QueryContext(ctx, selectAllContracts, isOnchain)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contract
	for rows.Next() {
		var i Contract
		if err := rows.Scan(
			&i.Script,
			&i.Type,
			&i.Label,
			&i.Address,
			&i.State,
			&i.CreatedAt,
			&i.OwnerKeyIndex,
			&i.OwnerKey,
			&i.SignerKey,
			&i.ExitDelay,
			&i.IsOnchain,
			&i.ExtraParams,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectAllTxs = `-- name: SelectAllTxs :many
SELECT txid, txid_type, amount, type, settled, created_at, hex, settled_by, asset_packet FROM tx
`

func (q *Queries) SelectAllTxs(ctx context.Context) ([]Tx, error) {
	rows, err := q.db.QueryContext(ctx, selectAllTxs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tx
	for rows.Next() {
		var i Tx
		if err := rows.Scan(
			&i.Txid,
			&i.TxidType,
			&i.Amount,
			&i.Type,
			&i.Settled,
			&i.CreatedAt,
			&i.Hex,
			&i.SettledBy,
			&i.AssetPacket,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectAllUtxos = `-- name: SelectAllUtxos :many
SELECT txid, vout, script, amount, spent_by, spent, tapscripts, spendable_at, created_at, delay_value, delay_type, tx from utxo
`

func (q *Queries) SelectAllUtxos(ctx context.Context) ([]Utxo, error) {
	rows, err := q.db.QueryContext(ctx, selectAllUtxos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Utxo
	for rows.Next() {
		var i Utxo
		if err := rows.Scan(
			&i.Txid,
			&i.Vout,
			&i.Script,
			&i.Amount,
			&i.SpentBy,
			&i.Spent,
			&i.Tapscripts,
			&i.SpendableAt,
			&i.CreatedAt,
			&i.DelayValue,
			&i.DelayType,
			&i.Tx,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectAllVtxos = `-- name: SelectAllVtxos :many
SELECT txid, vout, script, amount, commitment_txids, spent_by, spent, expires_at, created_at, preconfirmed, swept, settled_by, unrolled, ark_txid, asset_id, asset_amount FROM asset_vtxo_vw
`

func (q *Queries) SelectAllVtxos(ctx context.Context) ([]AssetVtxoVw, error) {
	rows, err := q.db.QueryContext(ctx, selectAllVtxos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssetVtxoVw
	for rows.Next() {
		var i AssetVtxoVw
		if err := rows.Scan(
			&i.Txid,
			&i.Vout,
			&i.Script,
			&i.Amount,
			&i.CommitmentTxids,
			&i.SpentBy,
			&i.Spent,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.Preconfirmed,
			&i.Swept,
			&i.SettledBy,
			&i.Unrolled,
			&i.ArkTxid,
			&i.AssetID,
			&i.AssetAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectAsset = `-- name: SelectAsset :one
SELECT asset_id, control_asset_id, metadata FROM asset WHERE asset_id = ?1
`

func (q *Queries) SelectAsset(ctx context.Context, assetID string) (Asset, error) {
	row := q.db.QueryRowContext(ctx, selectAsset, assetID)
	var i Asset
	err := row.Scan(&i.AssetID, &i.ControlAssetID, &i.Metadata)
	return i, err
}

const selectContractsByKeyIndexes = `-- name: SelectContractsByKeyIndexes :many
SELECT script, type, label, address, state, created_at, owner_key_index, owner_key, signer_key, exit_delay, is_onchain, extra_params, metadata FROM contract
WHERE owner_key_index IN (/*SLICE:indexes*/?)
`

func (q *Queries) SelectContractsByKeyIndexes(ctx context.Context, indexes []int64) ([]Contract, error) {
	query := selectContractsByKeyIndexes
	var queryParams []interface{}
	if len(indexes) > 0 {
		for _, v := range indexes {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:indexes*/?", strings.Repeat(",?", len(indexes))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:indexes*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contract
	for rows.Next() {
		var i Contract
		if err := rows.Scan(
			&i.Script,
			&i.Type,
			&i.Label,
			&i.Address,
			&i.State,
			&i.CreatedAt,
			&i.OwnerKeyIndex,
			&i.OwnerKey,
			&i.SignerKey,
			&i.ExitDelay,
			&i.IsOnchain,
			&i.ExtraParams,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectContractsByScripts = `-- name: SelectContractsByScripts :many
SELECT script, type, label, address, state, created_at, owner_key_index, owner_key, signer_key, exit_delay, is_onchain, extra_params, metadata FROM contract
WHERE script IN (/*SLICE:scripts*/?)
`

func (q *Queries) SelectContractsByScripts(ctx context.Context, scripts []string) ([]Contract, error) {
	query := selectContractsByScripts
	var queryParams []interface{}
	if len(scripts) > 0 {
		for _, v := range scripts {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:scripts*/?", strings.Repeat(",?", len(scripts))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:scripts*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contract
	for rows.Next() {
		var i Contract
		if err := rows.Scan(
			&i.Script,
			&i.Type,
			&i.Label,
			&i.Address,
			&i.State,
			&i.CreatedAt,
			&i.OwnerKeyIndex,
			&i.OwnerKey,
			&i.SignerKey,
			&i.ExitDelay,
			&i.IsOnchain,
			&i.ExtraParams,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectContractsByState = `-- name: SelectContractsByState :many
SELECT script, type, label, address, state, created_at, owner_key_index, owner_key, signer_key, exit_delay, is_onchain, extra_params, metadata FROM contract
WHERE state = ?1
`

func (q *Queries) SelectContractsByState(ctx context.Context, state string) ([]Contract, error) {
	rows, err := q.db.QueryContext(ctx, selectContractsByState, state)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contract
	for rows.Next() {
		var i Contract
		if err := rows.Scan(
			&i.Script,
			&i.Type,
			&i.Label,
			&i.Address,
			&i.State,
			&i.CreatedAt,
			&i.OwnerKeyIndex,
			&i.OwnerKey,
			&i.SignerKey,
			&i.ExitDelay,
			&i.IsOnchain,
			&i.ExtraParams,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectContractsByType = `-- name: SelectContractsByType :many
SELECT script, type, label, address, state, created_at, owner_key_index, owner_key, signer_key, exit_delay, is_onchain, extra_params, metadata FROM contract
WHERE type = ?1
`

func (q *Queries) SelectContractsByType(ctx context.Context, type_ string) ([]Contract, error) {
	rows, err := q.db.QueryContext(ctx, selectContractsByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contract
	for rows.Next() {
		var i Contract
		if err := rows.Scan(
			&i.Script,
			&i.Type,
			&i.Label,
			&i.Address,
			&i.State,
			&i.CreatedAt,
			&i.OwnerKeyIndex,
			&i.OwnerKey,
			&i.SignerKey,
			&i.ExitDelay,
			&i.IsOnchain,
			&i.ExtraParams,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectLatestContractByType = `-- name: SelectLatestContractByType :one
SELECT script, type, label, address, state, created_at, owner_key_index, owner_key, signer_key, exit_delay, is_onchain, extra_params, metadata FROM contract
WHERE type = ?1 AND is_onchain = ?2
ORDER BY owner_key_index DESC
LIMIT 1
`

type SelectLatestContractByTypeParams struct {
	Type      string
	IsOnchain bool
}

func (q *Queries) SelectLatestContractByType(ctx context.Context, arg SelectLatestContractByTypeParams) (Contract, error) {
	row := q.db.QueryRowContext(ctx, selectLatestContractByType, arg.Type, arg.IsOnchain)
	var i Contract
	err := row.Scan(
		&i.Script,
		&i.Type,
		&i.Label,
		&i.Address,
		&i.State,
		&i.CreatedAt,
		&i.OwnerKeyIndex,
		&i.OwnerKey,
		&i.SignerKey,
		&i.ExitDelay,
		&i.IsOnchain,
		&i.ExtraParams,
		&i.Metadata,
	)
	return i, err
}

const selectSpendableVtxos = `-- name: SelectSpendableVtxos :many
SELECT txid, vout, script, amount, commitment_txids, spent_by, spent, expires_at, created_at, preconfirmed, swept, settled_by, unrolled, ark_txid, asset_id, asset_amount FROM asset_vtxo_vw
WHERE spent = false AND unrolled = false
`

func (q *Queries) SelectSpendableVtxos(ctx context.Context) ([]AssetVtxoVw, error) {
	rows, err := q.db.QueryContext(ctx, selectSpendableVtxos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssetVtxoVw
	for rows.Next() {
		var i AssetVtxoVw
		if err := rows.Scan(
			&i.Txid,
			&i.Vout,
			&i.Script,
			&i.Amount,
			&i.CommitmentTxids,
			&i.SpentBy,
			&i.Spent,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.Preconfirmed,
			&i.Swept,
			&i.SettledBy,
			&i.Unrolled,
			&i.ArkTxid,
			&i.AssetID,
			&i.AssetAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectTxs = `-- name: SelectTxs :many
SELECT txid, txid_type, amount, type, settled, created_at, hex, settled_by, asset_packet FROM tx
WHERE txid IN (/*SLICE:txids*/?)
`

func (q *Queries) SelectTxs(ctx context.Context, txids []string) ([]Tx, error) {
	query := selectTxs
	var queryParams []interface{}
	if len(txids) > 0 {
		for _, v := range txids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:txids*/?", strings.Repeat(",?", len(txids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:txids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tx
	for rows.Next() {
		var i Tx
		if err := rows.Scan(
			&i.Txid,
			&i.TxidType,
			&i.Amount,
			&i.Type,
			&i.Settled,
			&i.CreatedAt,
			&i.Hex,
			&i.SettledBy,
			&i.AssetPacket,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectUtxo = `-- name: SelectUtxo :one
SELECT txid, vout, script, amount, spent_by, spent, tapscripts, spendable_at, created_at, delay_value, delay_type, tx
FROM utxo
WHERE txid = ?1 AND vout = ?2
`

type SelectUtxoParams struct {
	Txid string
	Vout int64
}

func (q *Queries) SelectUtxo(ctx context.Context, arg SelectUtxoParams) (Utxo, error) {
	row := q.db.QueryRowContext(ctx, selectUtxo, arg.Txid, arg.Vout)
	var i Utxo
	err := row.Scan(
		&i.Txid,
		&i.Vout,
		&i.Script,
		&i.Amount,
		&i.SpentBy,
		&i.Spent,
		&i.Tapscripts,
		&i.SpendableAt,
		&i.CreatedAt,
		&i.DelayValue,
		&i.DelayType,
		&i.Tx,
	)
	return i, err
}

const selectUtxosByTxid = `-- name: SelectUtxosByTxid :many
SELECT txid, vout, script, amount, spent_by, spent, tapscripts, spendable_at, created_at, delay_value, delay_type, tx
FROM utxo
WHERE txid = ?1
`

func (q *Queries) SelectUtxosByTxid(ctx context.Context, txid string) ([]Utxo, error) {
	rows, err := q.db.QueryContext(ctx, selectUtxosByTxid, txid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Utxo
	for rows.Next() {
		var i Utxo
		if err := rows.Scan(
			&i.Txid,
			&i.Vout,
			&i.Script,
			&i.Amount,
			&i.SpentBy,
			&i.Spent,
			&i.Tapscripts,
			&i.SpendableAt,
			&i.CreatedAt,
			&i.DelayValue,
			&i.DelayType,
			&i.Tx,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectVtxo = `-- name: SelectVtxo :many
SELECT txid, vout, script, amount, commitment_txids, spent_by, spent, expires_at, created_at, preconfirmed, swept, settled_by, unrolled, ark_txid, asset_id, asset_amount
FROM asset_vtxo_vw
WHERE txid = ?1 AND vout = ?2
`

type SelectVtxoParams struct {
	Txid string
	Vout int64
}

func (q *Queries) SelectVtxo(ctx context.Context, arg SelectVtxoParams) ([]AssetVtxoVw, error) {
	rows, err := q.db.QueryContext(ctx, selectVtxo, arg.Txid, arg.Vout)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssetVtxoVw
	for rows.Next() {
		var i AssetVtxoVw
		if err := rows.Scan(
			&i.Txid,
			&i.Vout,
			&i.Script,
			&i.Amount,
			&i.CommitmentTxids,
			&i.SpentBy,
			&i.Spent,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.Preconfirmed,
			&i.Swept,
			&i.SettledBy,
			&i.Unrolled,
			&i.ArkTxid,
			&i.AssetID,
			&i.AssetAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const settleVtxo = `-- name: SettleVtxo :exec
UPDATE vtxo
SET
    spent = true,
    spent_by = ?1,
    settled_by = COALESCE(?2, settled_by)
WHERE txid = ?3 AND vout = ?4
`

type SettleVtxoParams struct {
	SpentBy   sql.NullString
	SettledBy sql.NullString
	Txid      string
	Vout      int64
}

func (q *Queries) SettleVtxo(ctx context.Context, arg SettleVtxoParams) error {
	_, err := q.db.ExecContext(ctx, settleVtxo,
		arg.SpentBy,
		arg.SettledBy,
		arg.Txid,
		arg.Vout,
	)
	return err
}

const spendVtxo = `-- name: SpendVtxo :exec
UPDATE vtxo
SET
    spent = true,
    spent_by = ?1,
    ark_txid = COALESCE(?2, ark_txid)
WHERE txid = ?3 AND vout = ?4
`

type SpendVtxoParams struct {
	SpentBy sql.NullString
	ArkTxid sql.NullString
	Txid    string
	Vout    int64
}

func (q *Queries) SpendVtxo(ctx context.Context, arg SpendVtxoParams) error {
	_, err := q.db.ExecContext(ctx, spendVtxo,
		arg.SpentBy,
		arg.ArkTxid,
		arg.Txid,
		arg.Vout,
	)
	return err
}

const sweepVtxo = `-- name: SweepVtxo :exec
UPDATE vtxo
SET swept = true
WHERE txid = ?1 AND vout = ?2
`

type SweepVtxoParams struct {
	Txid string
	Vout int64
}

func (q *Queries) SweepVtxo(ctx context.Context, arg SweepVtxoParams) error {
	_, err := q.db.ExecContext(ctx, sweepVtxo, arg.Txid, arg.Vout)
	return err
}

const unrollVtxo = `-- name: UnrollVtxo :exec
UPDATE vtxo
SET unrolled = true
WHERE txid = ?1 AND vout = ?2
`

type UnrollVtxoParams struct {
	Txid string
	Vout int64
}

func (q *Queries) UnrollVtxo(ctx context.Context, arg UnrollVtxoParams) error {
	_, err := q.db.ExecContext(ctx, unrollVtxo, arg.Txid, arg.Vout)
	return err
}

const updateContractState = `-- name: UpdateContractState :execrows
UPDATE contract
SET
    state = ?1
WHERE script = ?2
`

type UpdateContractStateParams struct {
	State  string
	Script string
}

func (q *Queries) UpdateContractState(ctx context.Context, arg UpdateContractStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateContractState, arg.State, arg.Script)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTx = `-- name: UpdateTx :exec
UPDATE tx
SET
    created_at     = COALESCE(?1, created_at),
    settled        = CASE WHEN ?2 IS NOT NULL THEN TRUE ELSE settled END,
    settled_by    = COALESCE(?2, settled_by)
WHERE txid = ?3
`

type UpdateTxParams struct {
	CreatedAt sql.NullInt64
	SettledBy interface{}
	Txid      string
}

func (q *Queries) UpdateTx(ctx context.Context, arg UpdateTxParams) error {
	_, err := q.db.ExecContext(ctx, updateTx, arg.CreatedAt, arg.SettledBy, arg.Txid)
	return err
}

const updateUtxo = `-- name: UpdateUtxo :exec
UPDATE utxo
SET
    spent = CASE WHEN ?1 IS TRUE THEN TRUE ELSE spent END,
    spent_by = COALESCE(?2, spent_by),
    created_at = COALESCE(?3, created_at),
    spendable_at = COALESCE(?4, spendable_at)
WHERE txid = ?5 AND vout = ?6
`

type UpdateUtxoParams struct {
	Spent       interface{}
	SpentBy     sql.NullString
	CreatedAt   sql.NullInt64
	SpendableAt sql.NullInt64
	Txid        string
	Vout        int64
}

func (q *Queries) UpdateUtxo(ctx context.Context, arg UpdateUtxoParams) error {
	_, err := q.db.ExecContext(ctx, updateUtxo,
		arg.Spent,
		arg.SpentBy,
		arg.CreatedAt,
		arg.SpendableAt,
		arg.Txid,
		arg.Vout,
	)
	return err
}

const upsertAsset = `-- name: UpsertAsset :exec
INSERT INTO asset (asset_id, control_asset_id, metadata) VALUES (?1, ?2, ?3)
ON CONFLICT (asset_id) DO UPDATE SET
    control_asset_id = COALESCE(EXCLUDED.control_asset_id, control_asset_id),
    metadata = COALESCE(EXCLUDED.metadata, metadata)
`

type UpsertAssetParams struct {
	AssetID        string
	ControlAssetID sql.NullString
	Metadata       sql.NullString
}

func (q *Queries) UpsertAsset(ctx context.Context, arg UpsertAssetParams) error {
	_, err := q.db.ExecContext(ctx, upsertAsset, arg.AssetID, arg.ControlAssetID, arg.Metadata)
	return err
}
