name: ci_unit

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-sdk:
    name: Sdk unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '>=1.25.3'

      - run: go mod tidy

      - name: Check for changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "Changes detected after running go mod tidy"
            git diff
            exit 1
          fi

      - name: Check linting
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.5.0
          args: --timeout 5m

      - name: Check code integrity
        uses: securego/gosec@master
        with:
          args: '-severity high -quiet -exclude=G115 ./...'

      - name: Check unit tests
        run: make test